### PR TITLE
Make project version Optional

### LINKED ISSUE #6603: [Feature] Remove required 'version' from dbt_project.yml
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

At the moment, it is required that dbt projects include a `version` in their dbt_project.yml, which should be a semantic version, as mentioned in the dbt doc [here](https://docs.getdbt.com/reference/project-configs/version).

My dbt project is a git package with its own process for creating and publishing its semantic versioning. The semantic version is not hard coded in the code base, but it is generated semi-automatically by our CI/CD. I imagine this is a common practice.

Therefore our dbt project has 2 semantic versions, the one in `dbt_project.yml`, which does not serve any meaningful purpose according to the dbt doc, and the git semantic version (tag).

In summary, I suggest removing the required 'version' from dbt_project.yml, because:
- it does not serve any purpose
- it is confusing as it is potentially in conflict with the git repo's own versioning.

### Describe alternatives you've considered

_No response_

### Who will this benefit?

All?

### Are you interested in contributing this feature?

Sure

### Anything else?

https://docs.getdbt.com/reference/project-configs/version

### PR DESCRIPTION
**Pull request by seub**
resolves #6603 

### Description

I changed `Project.version` to `Optional` (default `None`) in core/dbt/config and core/dbt/contracts. 

(This change was suggested by @jtcohen6 in the issue #6603)

This config was not being used by dbt, so I believe no further changes are needed. `make test` and `make integration` both passed.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by seub** [comment]
I fixed my email in the last (empty) commit, so the cla-bot must be triggered by the first two commits. But I don't think I can change them now.

**Comment by jtcohen6** [comment]
@seub Could you try `git rebase`, to squash your previous commits together?

**Comment by seub** [comment]
I rewrote the email in the faulty commits using [this](https://stackoverflow.com/a/2931914/1367124) and then I did `git push`. But clearly something is not working. I'll just close this MR and create a new one.

**Comment by seub** [comment]
New PR: https://github.com/dbt-labs/dbt-core/pull/6718

**Pull request closed without merging**
