### PR TITLE
Add space before justification periods

### LINKED ISSUE #4737: [CT-246] [Feature] Have a space after model name before the alignment periods, for ease of double-click selection
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

In VS Code, double-clicking a model name selects it and all of the dots that line up the results:
image
```
07:00:06  1 of 1 START seed file dbt_jlabes.data_star_aggregate_expected.................. [RUN]
07:00:18  1 of 1 OK loaded seed file dbt_jlabes.data_star_aggregate_expected.............. [INSERT 3 in 11.49s]
```

If there was a space after expected and before the first period, it wouldn't select them all

### Describe alternatives you've considered

Using dbt Cloud in Chrome, which has different word boundary calculation logic

### Who will this benefit?

VS Code users, maybe other IDEs? 

### Are you interested in contributing this feature?

Sure

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joellabes**
resolves #4737

### Description
From the hard-to-select
```
03:48:20  1 of 1 OK loaded seed file dbt_jlabes.stg_server_farm_cities.................... [INSERT 4 in 6.58s]
```

to the easy-to-select 
```
03:48:20  1 of 1 OK loaded seed file dbt_jlabes.stg_server_farm_cities ................... [INSERT 4 in 6.58s]
```

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change

### CODE REVIEW

**Comment by joellabes** [comment]
It looks like the error is 
```
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/markupsafe/__init__.py)
```

I dont think this is me - any ideas?

**Comment by joellabes** [comment]
Maybe this is it: https://github.com/dbt-labs/dbt-core/issues/4745

**Review by ChenyuLInx — APPROVED** [review]
Looks good to me, for the pipeline issue I think you just need to rebase main again

**Review by leahwicz — APPROVED** [review]
Thanks Joel!

**Pull request merged**
