### PR TITLE
fixed minor typos

### LINKED ISSUE #6529: [CT-1752] [Bug] Small typos related to the interactive profile set up
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I believe `interative` is a typo of `interactive`

https://github.com/dbt-labs/dbt-core/blob/54538409509e0d677876f1102aa3bc0c67007278/core/dbt/cli/params.py#L272-L274
https://github.com/dbt-labs/dbt-core/blob/60f80056b1b09b35a22ac91c93319827bdac0e0e/core/dbt/main.py#L348-L356
https://github.com/dbt-labs/dbt-core/blob/b3440417ad1e38a40c488c3632a63f5d2e0c88f4/core/dbt/docs/build/html/index.html#L321-L325

### Expected Behavior

Fix typos:

-  `interative` to `interactive`

### Steps To Reproduce

1. Run `dbt init --h` 

### Relevant log output

```shell
N/A
```

### Environment

```markdown
- OS:Ubuntu 22.04.1
- Python: 3.10.6
- dbt: 1.1.3
```

### Which database adapter are you using with dbt?

_No response_

### Additional Context

N/A

### PR DESCRIPTION
**Pull request by nshuman1**
resolves #6529

No issue created (updating comments and docs)

### Description

Corrects some minor typos that have been bugging me for a while.

### Checklist

- [ ✓] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ✓] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ✓] I have run this code in development and it appears to resolve the stated issue
- [ ✓] This PR includes tests, or tests are not required/relevant for this PR
- [ ✓] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ✓] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
@nshuman1 Thanks for the PR! I know this is just fixing some typos. Could I still ask you to open a quick issue for it, and add a changelog entry? We want to be able to give you credit in the release notes after merging!

**Comment by jtcohen6** [comment]
@nshuman1 Looks like there's just a last little bit of reformatting:

```
If you are seeing this message in CI, reproduce locally with: `pre-commit run --all-files`.
To run `pre-commit` as part of git workflow, use `pre-commit install`.
All changes made by hooks:
diff --git a/core/dbt/cli/params.py b/core/dbt/cli/params.py
index 77cbf0e..b739e88 1006[44](https://github.com/dbt-labs/dbt-core/actions/runs/3847710753/jobs/6555228716#step:5:45)
--- a/core/dbt/cli/params.py
+++ b/core/dbt/cli/params.py
@@ -270,7 +270,7 @@ show = click.option(
 )
 
 skip_profile_setup = click.option(
-        "--skip-profile-setup", "-s", envvar=None, help="Skip interactive profile setup.", is_flag=True
+    "--skip-profile-setup", "-s", envvar=None, help="Skip interactive profile setup.", is_flag=True
 )
 ```
 
You can make that change manually, or (better) install `pre-commit` and run it to make the change for you: https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#pre-commit

**Comment by nshuman1** [comment]
@jtcohen6 ran pre-commit, fixed linter error.

**Review by ChenyuLInx — APPROVED** [review]
LGTM! Thanks for fixing these

**Pull request merged**
