### PR TITLE
Remove tmp file after test passed

### PR DESCRIPTION
**Pull request by bbroeksema**
resolves 5631

### Description

This pull request improves a test case by removing a tmp file that is created during test execution. The resolution has been verified by following the steps to reproduce as described in: https://github.com/dbt-labs/dbt-core/issues/5631 and verifying that after this fix the file is indeed removed. This PR adds the rm_file from `dbt.tests.utils` to remove the specific file.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

I haven't add a changelog entry yet, does that make sense for fixing a test?

### CODE REVIEW

**Comment by bbroeksema** [comment]
I've added the email address which I used to sign the CLA to my github account. Do I need to to anything else to make the check pass?

**Comment by gshank** [comment]
@cla-bot check

**Review by jtcohen6 — COMMENTED** [review]
@bbroeksema Could you [add a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)? We don't usually require one for changes to tests only, but it's also our way of giving you credit for your contribution :)

**Comment by bbroeksema** [comment]
@jtcohen6 done.

**Review by gshank — APPROVED** [review]

**Pull request merged**
