### PR TITLE
add publication artifact to schemas

### PR DESCRIPTION
**Pull request by MichelleArk**
resolves https://github.com/dbt-labs/dbt-core/issues/7591

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by gshank** [comment]
The schema that's generated has all kinds of unnecessary definitions, like ManifestMetadata, etc. I'm not sure how they got in there. hologram must be doing something weird. I haven't done a lot of looking at the jsonschema output that hologram spits out, but this feels wrong to me.

**Comment by gshank** [comment]
It looks like all of the descriptions from all of the classes in the collect-artifact-schema.py are included. If I comment out the other ones and run it for just PublicationArtifact it's correct. The "definitions" in hologram must be getting persisted across invocations of json_schema.

**Comment by gshank** [comment]
Maybe adding the ability to specify just one schema to collect might help. It's always irritating to get rid of the unnecessary schema updates when running this script anyway.

**Comment by MichelleArk** [comment]
> Maybe adding the ability to specify just one schema to collect might help. It's always irritating to get rid of the unnecessary schema updates when running this script anyway.

It really is! Taking a stab at that here: https://github.com/dbt-labs/dbt-core/pull/7599

**Comment by MichelleArk** [comment]
> The "definitions" in hologram must be getting persisted across invocations of json_schema.
Would you mind making an issue for this and we can dig into it separately? For now I've just kept `WriteableManifest` as the last artifact class as a short-term workaround.

**Review by gshank — APPROVED** [review]

**Pull request merged**
