### PR TITLE
Andy/fix init comment

### PR DESCRIPTION
**Pull request by andy-clapson**
resolves https://github.com/dbt-labs/dbt-core/issues/5791

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
Hey @andy-clapson, thanks for the contribution! Two questions:
- Are you able to sign the CLA? If not, we won't be able to accept the changes unfortunately :( even though they're super small!
- If you are able, could you open a super quick issue for the change, just so we can track it in our changelog?

**Comment by andy-clapson** [comment]
> Hey @andy-clapson, thanks for the contribution! Two questions:
> 
>     * Are you able to sign the CLA? If not, we won't be able to accept the changes unfortunately :( even though they're super small!
> 
>     * If you are able, could you open a super quick issue for the change, just so we can track it in our changelog?

Yep, done. Issue is here: https://github.com/dbt-labs/dbt-core/issues/5791

**Comment by andy-clapson** [comment]
@jtcohen6 I've done all this, and added the changelog entry as well

**Review by emmyoop — APPROVED** [review]
@andy-clapson thanks for correcting this comment!  

As for the test, you're right that it should be defined as a constant.  We're in the middle of an effort to convert tests and this one has still not been done!  The framework we are moving to will make it very easy to make this into a constant and we will take care of it when we move this over.  Thanks for pointing out that need.  I created https://github.com/dbt-labs/dbt-core/issues/6010 for the conversion and made a note to make sure we do just that.

**Pull request merged**
