### PR TITLE
Update link to `dbt` install docs

### PR DESCRIPTION
**Pull request by ryancharris**
resolves #

### Description

This PR updates the dbt installation link in the repo's README.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by ChenyuLInx** [comment]
@ryancharris  can you please add a change log entry so we can properly credit you in the release note? Instruction [here](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-or-modifying-a-changelog-entry)

**Review by ChenyuLInx — APPROVED** [review]
Thanks @ryancharris  for updating the link!

**Comment by ryancharris** [comment]
> @ryancharris can you please add a change log entry so we can properly credit you in the release note? Instruction [here](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-or-modifying-a-changelog-entry)

Absolutely!

**Comment by ryancharris** [comment]
@ChenyuLInx Added the changelog entry!

**Comment by ChenyuLInx** [comment]
@ryancharris thanks for the quick reply! One last thing before we can merge your change, have you signed the CLA mentioned [here](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#notes)?

**Comment by ryancharris** [comment]
> @ryancharris thanks for the quick reply! One last thing before we can merge your change, have you signed the CLA mentioned [here](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#notes)?

I have! Signed it yesterday -- not sure why CI isn't reflecting that 🤔

**Comment by ChenyuLInx** [comment]
@ryancharris  Merged! Thanks for contributing this!!!

**Pull request merged**
