### PR TITLE
print warning and error output for source freshness checks

### LINKED ISSUE #6248: [Feature] Freshness checks should repeat errored tests at the end
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

DBT's command `dbt source freshness` performs a test against all sources in a project. However if there are a long list of sources, say 70+, one error or warning gets lost in the results printed at the end. Additionally there is no text printed that lets a user know *any* test failed.

Screen Shot 2022-11-14 at 3 56 39 PM

There were 2 failures and 2 warns on that run. I would like to propose a final paragraph similar to `dbt test` that lists all failed source checks, and lists warnings.

### Describe alternatives you've considered

_No response_

### Who will this benefit?

CI and Manual runs of source freshness checks will be easier to mentally parse with a summary block at the end of a run. Additionally printed text of the result, rather than only relying on exit codes, would be appreciated. 

### Are you interested in contributing this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by justbldwn**
resolves #6248

### Description

attached is a first go at building off of @jtcohen6 's idea for what printed freshness output could look like in #6248 . this adds a new function `format_age()` that can take in a dynamic age and create a more human friendly way of reading how long a source has not met a defined freshness guideline. this will also take into consideration pluralizing the hours/minutes/seconds if a value is 1 hour/minute/second respectively. please let me know if there are any requests for changes/other methods of doing this, would be happy to make any necessary changes.

here is an example `models/sources.yml` file:
```yaml
version: 2

sources:
  - name: sandbox
    database: postgres
    schema: sandbox
    freshness:
      warn_after:
        count: 1
        period: minute
      error_after:
        count: 5
        period: day
    loaded_at_field: last_updated

    tables:
      - name: my_src_error
      - name: my_src_warn
      - name: my_src_fresh

```

here is an output of what this looks like when running `dbt source freshness` locally: 

```
dbtcore ❯ dbt source freshness
14:51:49  Running with dbt=1.4.0-a1
14:51:49  Found 5 models, 20 tests, 0 snapshots, 0 analyses, 289 macros, 0 operations, 3 seed files, 3 sources, 0 exposures, 0 metrics
14:51:49  
14:51:49  Concurrency: 4 threads (target='dev')
14:51:49  
14:51:49  1 of 3 START freshness of sandbox.my_src_error ................................. [RUN]
14:51:49  2 of 3 START freshness of sandbox.my_src_fresh ................................. [RUN]
14:51:49  3 of 3 START freshness of sandbox.my_src_warn .................................. [RUN]
14:51:49  1 of 3 ERROR STALE freshness of sandbox.my_src_error ........................... [ERROR STALE in 0.04s]
14:51:49  2 of 3 PASS freshness of sandbox.my_src_fresh .................................. [PASS in 0.04s]
14:51:49  3 of 3 WARN freshness of sandbox.my_src_warn ................................... [WARN in 0.04s]
14:51:49  
14:51:49  Completed with 1 error and 1 warning:
14:51:49  
14:51:49  Failure in source my_src_error (models/sources.yml)
14:51:49  Last updated 84 days, 1 hour, 1 minute, 18.181089 seconds ago. Expected no more than 5 days.
14:51:49  
14:51:49  Warning in source my_src_warn (models/sources.yml)
14:51:49  Last updated 1 day, 20 hours, 1 minute, 26.368388 seconds ago. Expected no more than 1 minute.
14:51:49  
14:51:49  Done. PASS=1 WARN=1 ERROR=1 SKIP=0 TOTAL=3
```
### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by justbldwn** [comment]
hello! i'm marking this as ready for review, but fully understand that an integration test is failing. i'm happy to try and make changes to the tests, but after trying some fixes locally, i wasn't able to not get `test_source_freshness_error` and `test_runtime_error_states` to pass. 

if someone could help point out what the root issue may be for these, i'm happy to contribute changes to the tests to ensure that everything is passing, just may need some help. thanks in advance for any review/feedback!

**Comment by gshank** [comment]
The "task_end_messages" for the freshness task (in core/dbt/task/freshness.py) calls "print_run_result_error" which doesn't handle the freshness status codes. That method is already filing a FreshnessCheckComplete messages. Probably you need to skip using "print_run_result_error" and either modify FreshnessCheckComplete to handle the error condition or create a new logging event.

**Comment by justbldwn** [comment]
hi @gshank ! sorry for the delay in getting back to this PR. 

after doing some additional digging into this, i found that the reason for the 2 failing tests was due to `interpret_run_result()` in `core/dbt/task/printer.py` didn't include `NodeStatus.RuntimeErr` as a possible option (even though `SourceFreshnessRuntimeError` uses this enum). now that i added `NodeStatus.RuntimeErr` to the list of possible options in `interpret_run_result()` and the tests should now be passing. 

if you or someone else on the team would be able to review this, that'd be great - thank you! 👍

**Comment by emmyoop** [comment]
@justbldwn sorry this has taken so long for us to get to.  Would you mind resolving the conflicts that are now present so we can verify all the tests are passing?

**Comment by gshank** [comment]
If you want to continue to work on it that's fine, but I'd prefer that we not change the other run results. Would it be possible to limit the changes to the freshness code?

**Comment by gshank** [comment]
@peterallenwebb is going to take another look at this, because he's working in a related area right now.

**Comment by justbldwn** [comment]
great, thank you for the update!

**Pull request closed without merging**
