### PR TITLE
fix conflict for real not minimal snowplow tracker

### PR DESCRIPTION
**Pull request by akurdyukov**
From #8719

Closes https://github.com/dbt-labs/dbt-core/issues/8719

### Problem

Instaling `dbt-core` with `meltano` in the same virtualenv breaks dbt because contract conflict between `minimal-snowplow-tracker` (dependency of dbt) and `snowplow-python-tracker`.

### Solution

Adds explicit version check and use `minimal` or `full` contract call.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by graciegoheen** [comment]
Hey - thanks so much for opening this up! Is there is a reason you targeted the `1.4.latest` branch? We typically target the `main` branch and backport as needed.

**Comment by dbeatty10** [comment]
Temporarily added `Skip Changelog` label so that we can see if this passes the CI checks (minus the check for a changelog).

This label should be removed prior to final review + merge.

**Comment by akurdyukov** [comment]
> Hey - thanks so much for opening this up! Is there is a reason you targeted the `1.4.latest` branch? We typically target the `main` branch and backport as needed.

Yes, I needed get it working with dbt-clickhouse which is compatible with 1.4 only. I can open new PR to `main` after I fix build errors.

**Comment by akurdyukov** [comment]
I'm not sure if it's correct but I fixed mypy error by ignoring.

**Comment by graciegoheen** [comment]
Hey @akurdyukov - I tried to re-point this PR to the main branch, but got a handful of merge conflicts. Would you be able to take a look? Thanks!

**Comment by edgarrmondragon** [comment]
@graciegoheen do you think this PR can be salvaged or is it better to start a fresh one targeting `main`?

**Comment by dbeatty10** [comment]
> @graciegoheen do you think this PR can be salvaged or is it better to start a fresh one targeting `main`?

@edgarrmondragon A fresh one targeting the `main` branch seems like the way to go here.

In the meantime, I switched this PR back to targeting the `1.4.latest` branch to make it easier to see the original diff.

**Comment by seunggs** [comment]
Is there any progress on this? Running into the same issue working with Meltano + dbt

**Comment by edgarrmondragon** [comment]
> Is there any progress on this @edgarrmondragon? Running into the same issue working with Meltano + dbt

@seunggs I got https://github.com/dbt-labs/dbt-core/pull/9528 started

**Comment by dbeatty10** [comment]
Thanks for doing that @edgarrmondragon 🙏 

Closing this one in favor of #9528

**Comment by seunggs** [comment]
@edgarrmondragon Thank you for the update 🙏 Will track that issue!

**Pull request closed without merging**
