### PR TITLE
add adapter_response for test

### LINKED ISSUE #2964: [CT-1635] Populate adapter_response for tests + sources
### Describe the feature
#2747 requested that dbt log bytes processed for _all_ query types, including tests, source-freshness, and run-operations. This prompted the first part of a solution in #2961: adding an `adapter_response` dict to record database-specific information about the queries dbt has run. In v0.19.0, that will include `bytes_processed` for all materializations (model runs, seeds, snapshots).

We'd like to record bytes processed for tests and source snapshots, too. What does this really mean?
- `dbt test` should populate `adapter_response` in `run_results.json`
- `dbt source snapshot-freshness` should populate `adapter_response` in `sources.json` 

(I'm less clear on how we'd manage this in `run-operation`, since it doesn't write to `run_results`.)

Eventually, this has the potential to dovetail nicely with:
- #2079: add a new log line to the "summary" stdout, with the total bytes processed from the invocation. In an ideal world, users could get a human-friendly rounded number in stdout and the raw numbers in `run_results.json` for analysis/aggregation.
- #2580: the ability to define which result information is populated to `message` in stdout (maybe via Jinja macro??)

### Describe alternatives you've considered
- Not doing this

### Additional context
- Most immediately relevant to BigQuery (bytes processed)
- Useful for any database which sends back significant information in its response

### Who will this benefit?
- Projects with larger datasets, where filtering is important to limit cost of test queries

### PR DESCRIPTION
**Pull request by aezomz**
Add adapter_response for dbt test

resolves #2964
or partial resolve?

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by aezomz** [comment]
Can we check which test is failing?

**Review by ChenyuLInx — COMMENTED** [review]
Thanks for contributing! This looks good! Can we also do similar thing for freshness task?
Also do you think you can look up functional tests that test those two functions and add some  test there?([link](https://github.com/dbt-labs/dbt-core/blob/85e415f50f58c72f347671212d054efccd61b68c/tests/functional/sources/test_source_freshness.py#L106) for freshness, for test maybe add some additional check [here](https://github.com/dbt-labs/dbt-core/blob/bdff19d9099435bfbecf5ff429fbd903ea91d308/tests/functional/custom_singular_tests/test_custom_singular_tests.py#L105)?)
How to run functional tests([link](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#testing)). Once you setup you can also just do `pytest testfilename.py`

**Comment by aezomz** [comment]
> Thanks for contributing! This looks good! Can we also do similar thing for freshness task? Also do you think you can look up functional tests that test those two functions and add some test there?([link](https://github.com/dbt-labs/dbt-core/blob/85e415f50f58c72f347671212d054efccd61b68c/tests/functional/sources/test_source_freshness.py#L106) for freshness, for test maybe add some additional check [here](https://github.com/dbt-labs/dbt-core/blob/bdff19d9099435bfbecf5ff429fbd903ea91d308/tests/functional/custom_singular_tests/test_custom_singular_tests.py#L105)?) How to run functional tests([link](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#testing)). Once you setup you can also just do `pytest testfilename.py`

Can u share where can I get the adapter response for freshness? I couldn't find it
https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/base/impl.py#L1072

Big thank you for pointing me to the test that i should update with.

**Comment by jtcohen6** [comment]
Seconding, thanks for the contribution @aezomz!

> Can u share where can I get the adapter response for freshness? I couldn't find it
https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/adapters/base/impl.py#L1072

Check out this comment from a few months ago: https://github.com/dbt-labs/dbt-core/issues/2964#issuecomment-1315379652

And this commit (though might need some rework given other changes): https://github.com/dbt-labs/dbt-core/commit/a066c1e8bbdd54d7b8d658b1c3eb905d756606bf

**Comment by aezomz** [comment]
@jtcohen6 , thanks for the guidance. I will never figure this out on my own.

There is some mypy errors that i suppressed since its returning AttrDict now, feel free to suggest a better way.
I think some pytest to ensure all is passing. But will see from CI if there are anything else breaking.

**Comment by elyobo** [comment]
:tada: thanks @aezomz!

**Pull request merged**
