### PR TITLE
Run dbt on WebAssembly

### PR DESCRIPTION
**Pull request by arieldbt**
### Description

Fixes for the linter on this PR: https://github.com/dbt-labs/dbt-core/pull/5803

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [X] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [X] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [X] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by arieldbt** [comment]
unit tests pass, these integration tests fail for me locally (not sure if my setup is bad):

full logs are here: https://gist.github.com/arieldbt/7a5d742ecfe64e75f17bbb9d898e33b1

```
============================================ short test summary info ============================================
FAILED tests/adapter/dbt/tests/adapter/grants/test_model_grants.py::TestModelGrants::test_view_table_grants - assert 0 == 3
FAILED tests/adapter/dbt/tests/adapter/grants/test_incremental_grants.py::TestIncrementalGrants::test_incremental_grants - assert 0 == 3
FAILED tests/adapter/dbt/tests/adapter/grants/test_invalid_grants.py::TestInvalidGrants::test_invalid_grants - dbt.exceptions.ParsingException: Parsing Error
FAILED tests/adapter/dbt/tests/adapter/grants/test_snapshot_grants.py::TestSnapshotGrants::test_snapshot_grants - dbt.exceptions.ParsingException: Parsing Error
FAILED tests/adapter/dbt/tests/adapter/grants/test_seed_grants.py::TestSeedGrants::test_seed_grants - dbt.exceptions.ParsingException: Parsing Error
========================================= 5 failed, 76 passed in 20.55s =========================================
ERROR: InvocationError for command /Users/ariel/code/dbt-core/.tox/py-integration/bin/python -m pytest --cov=core -nauto tests/adapter (exited with code 1)
____________________________________________________ summary ____________________________________________________
ERROR:   py-integration: commands failed
```

**Comment by arieldbt** [comment]
Annnnnd I got the integration tests to pass by running this command instead (updated the full log):

https://gist.github.com/arieldbt/7a5d742ecfe64e75f17bbb9d898e33b1

`% DBT_TEST_USER_1=dbt_test_user_1 DBT_TEST_USER_2=dbt_test_user_2 DBT_TEST_USER_3=dbt_test_user_3 make integration > integration.log 2>&1`

**Comment by jtcohen6** [comment]
@arieldbt Thanks for reopening! Most of these changes look reasonable. I'm excited that they actually leave us with cleaner / more pluggable interfaces for things like external requests. And the new click CLI &rarr; top-level APIs should make it even easier to invoke `dbt-core` programmatically, as a library.

Considerations:
- The dynamic inclusion/exclusion of `"dbt-extractor~=0.4.1"` as an installation dependency might move us even further away from our ability to eventually support Poetry / `pyproject.toml`: https://github.com/dbt-labs/dbt-core/issues/5696
- We'd want _some_ sort of CI check to verify that dbt-on-pyodide works on an ongoing basis. Otherwise, we risk making changes that break compatibility without knowing.

Ultimately, I think the folks on the Execution team are best situated to review this.

**Comment by jtcohen6** [comment]
Going to close this one for now. It remains a very cool idea—but not something we can make immediate progress on, nor do we have a tangible use case that we can invest in supporting on an ongoing basis.

**Pull request closed without merging**
