### PR TITLE
[fix] Fix the partial parse write path

### LINKED ISSUE #6055: [CT-1337] [Bug] dbt is writing `target/partial_parse.msgpack` in current working directory and not using config's project-dir
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

This [line](https://github.com/dbt-labs/dbt-core/blob/558468e85480c2f25fa7742d7d3d54ee813524d1/core/dbt/parser/manifest.py#L546) is creating a new relative path to the `target` folder instead of an absolute path as [this line](https://github.com/dbt-labs/dbt-core/blob/558468e85480c2f25fa7742d7d3d54ee813524d1/core/dbt/parser/manifest.py#L643) is correctly doing.

### Expected Behavior

To store `partial_parse.msgpack` in the right folder. Right now, it could create it in current working directory instead of `project-dir`.

### Steps To Reproduce

Couldn't find a way to reproduce it using dbt commands. It is happening on [sqlfluff dbt templater](https://github.com/sqlfluff/sqlfluff) when using `dbt.parser.manifest` to read manifest.

### Relevant log output

_No response_

### Environment

```markdown
- OS: any
- Python: 3.8
- dbt: 1.3
```

### Which database adapter are you using with dbt?

postgres, redshift, snowflake, bigquery, spark

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by z3z1ma**
resolves #6055 

Partial parse should use project root or it does not resolve to correct path. 
Eg. `target-path: ../some/dir/target`, if not ran from root, creates an erroneous folder.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by z3z1ma** [comment]
Signed

Please label this hackathon, lets go haha

**Review by gshank — CHANGES_REQUESTED** [review]
The change is fine :). But it needs to have "pre-commit run --all-files" run to fix the formatting issue (pip install pre-commit if you don't have it installed), and run "changie new" to create a changelog entry.

**Comment by jtcohen6** [comment]
Yo @z3z1ma, great to see you hacking in here! :)

Are you up to fix the pre-commit checks and add a changelog entry?

**Comment by z3z1ma** [comment]
Yeah for sure. Will get to it this weekend :)

**Comment by frannydelaney** [comment]
Oo I need this :)

**Comment by derek-hackett-procore** [comment]
Same here

**Review by gshank — APPROVED** [review]

**Pull request merged**
