### PR TITLE
Add date spine macros to core

### LINKED ISSUE #8172: [CT-2855] [Feature] dbt_utils.date_spine should be added to core given new MetricFlow requirements
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The new metric spec requires a Time Spine model - documented [here](https://docs.getdbt.com/docs/build/metricflow-time-spine). 

The `metricflow_time_spine` model to copy/paste into your project uses the dbt_utils `date_spine` macro. Given that this macro will be used by all dbt users who want to define metrics, should we bring it into dbt-core? 

Additionally, should we handle casting within the macro itself? Currently, the example requires that you input appropriate casting to a date data type:
```
    {{dbt_utils.date_spine('day'
    , "to_date('01/01/2000','mm/dd/yyyy')"
    , "to_date('01/01/2027','mm/dd/yyyy')"
    )
    }}
```
But not all warehouses have the `to_date` function. If we handled date casting within the `date_spine` macro, we could have a single `metricflow_time_spine` example that would work in all data warehouses.

### Describe alternatives you've considered

We keep `date_spine` in `dbt_utils` and require that people install `dbt_utils` if they want to use metric flow.

### Who will this benefit?

dbt users who want to define metrics in their project

### Are you interested in contributing this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by QMalcolm**
resolves #8172

### Problem

The [date_spine macro in dbt-utils](https://github.com/dbt-labs/dbt-utils/blob/6ba7b660b1d1b4e3b41cb0cf6c3c0e4a70ae54e4/macros/sql/date_spine.sql#L26) is getting used more regularly due to the semantic layer requiring a date spine model to exist. As such we should start including it with dbt-core instead of requiring people to get dbt-utils to do it. Additionally, as #8319 suggests, we want to begin auto generating the metricflow date spine model when semantic objects exist but the required date spine model does not. In that vein, this is a required precursor.

### Solution

Move the macros into dbt-core 🚀

__Note__
We've also created adapter tests. To ensure the macros work in the specific adapters we maintain, I've opened branches on dbt-snowflake, dbt-redshift, and dbt-bigquery to run the tests. And I've run the tests in those branches against this branch of core.

| Repo | Branch| Integration Test Run |
|--------|--------|--------|
| [dbt-bigquery](https://github.com/dbt-labs/dbt-bigquery) | [qmalcolm--date-spine-utils-testing](https://github.com/dbt-labs/dbt-bigquery/tree/qmalcolm--date-spine-utils-testing) | [Passing](https://github.com/dbt-labs/dbt-bigquery/actions/runs/6277421783) |
| [dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake) | [qmalcolm--date-spine-utils-testing](https://github.com/dbt-labs/dbt-snowflake/tree/qmalcolm--date-spine-utils-testing) | [Passing](https://github.com/dbt-labs/dbt-snowflake/actions/runs/6277413556) |
| [dbt-redshift](https://github.com/dbt-labs/dbt-redshift) | [qmalcolm--date-spine-utils-testing](https://github.com/dbt-labs/dbt-redshift/tree/qmalcolm--date-spine-utils-testing) | [Passing](https://github.com/dbt-labs/dbt-redshift/actions/runs/6277411080) | 

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [X] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by QMalcolm** [comment]
> Is there a deprecation plan in place for these macros in dbt-utils? If the implementations of the two diverge this could lead to some surprising behaviour - especially if dbt-utils is installed and its date spine macros take precedence over the ones defined in core ([I _think_ that's how the precedence works based on docs](https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch#:~:text=Package%20always%20wins%20%E2%80%94%20As%20the,any%20way%20to%20override%20them.))

Yes! Once this is merged I'm going to open a ticket on [dbt-labs/dbt-utils](https://github.com/dbt-labs/dbt-utils/) that either I or @dbeatty10 (I believe) will take on. I found the [old deprecation function before it's removal](https://github.com/dbt-labs/dbt-utils/pull/733/commits/6f5f414efb49b3b397b35f9a0454df5ac0c3561b), and I talked with @joellabes that it's fine to bring back.

**Review by ChenyuLInx — APPROVED** [review]
Thanks for moving this!!!

I remember there were conversations about moving `dbt-utils` into core. Are we still thinking of doing it? @dbeatty10

**Comment by dbeatty10** [comment]
> I remember there were conversations about moving `dbt-utils` into core. Are we still thinking of doing it? @dbeatty10

At this point in time, only planning on moving `date_spine` into dbt-core.

**Comment by graciegoheen** [comment]
@dbeatty10 do we need to make any updates to dbt_utils docs? Or are we ok here?

**Comment by dbeatty10** [comment]
@graciegoheen https://github.com/dbt-labs/dbt-utils/issues/839 should also include any relevant update to the docs in dbt_utils, so added docs updates to the acceptance criteria of that issue.

**Pull request merged**
