### PR TITLE
remove source quoting setting in adapter tests

### LINKED ISSUE #5836: [Bug] Adapter doc tests override adapter quoting settings
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The adapter tests for references in generated documentation define quoting policies for sources. By defining these policies, they override the default quoting policy set by the adapter.

### Expected Behavior

Use the default adapter quoting policies in the adapter tests.

### Steps To Reproduce

Implement a test based on `BaseDocsGenReferences`

### Relevant log output

_No response_

### Environment

```markdown
dbt-tests-adapter==1.2.1
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

It makes sense for users of the adapters to specify their own quoting policies, but in this case every adapter maintainer would have to remove these quoting policies so that their tests would succeed. I think it doesn't really make sense to have these as part of the tests.

E.g. in my case one of the databases we run our tests on contains a `-` in its name. The adapter's quoting policy sets all database names to be quoted, but this is overridden in the source for this test so the test failed on that particular database.

### PR DESCRIPTION
**Pull request by sdebruyn**
resolves #5836 

### Description

As discussed in #5836, the adapter tests should not override the quoting policies defined in the adapters. I removed all quoting policies from this the docs generate test.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by sdebruyn** [comment]
I just had the same build failure in the dbt-sqlserver GH Actions as [this one(https://github.com/dbt-labs/dbt-core/actions/runs/3054923370/jobs/4927427142), something we can do about it or just ignore and retry?

**Comment by ChenyuLInx** [comment]
It looks like there's some issue regarding pulling down `setup-tools`, maybe just retry in a bit.

As for the change, they look good to me! @gshank what was the reason those quoting setting were added in the beginning, do we expect this to break tests in other adapter repos?

**Comment by gshank** [comment]
Setting the quoting was copied from the earlier integration tests. It's quite possible that it was originally there because we ran multiple adapter tests on the same test suite? I think we might want to check what this does to the tests in Redshift, BigQuery, and Snowflake before merging though. If it breaks those tests we'd have to quickly do PRs to fix.

**Comment by ChenyuLInx** [comment]
Created a [test pr](https://github.com/dbt-labs/dbt-bigquery/pull/314) to test this change in dbt-bigquery repo

**Review by ChenyuLInx — APPROVED** [review]

**Comment by ChenyuLInx** [comment]
The tests in test PR works as expected, so I think this is good to go. @sdebruyn  Thanks for contributing it!!

**Pull request merged**
