### PR TITLE
Refactor code to properly handle reference deprecations

### LINKED ISSUE #10833: [Regression] 1.9.pre lost the warning at the project level (i.e. start of the run) that notified users that a model depends on a now deprecated model
### Is this a regression in a recent version of dbt-core?

- [X] I believe this is a regression in dbt-core functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Pre-1.9 (1.8, 1.7), dbt emitted a "project level" warning that a model was using a now deprecated model. This seems to have been removed in 1.9 (versionless in dbt Cloud).

### Expected/Previous Behavior

Bring that warning back :) 

### Steps To Reproduce

Project setup:

```yaml
# dbt_project.yml
name: my_dbt_project
profile: all
config-version: 2
version: "1.0.0"

models:
  my_dbt_project:
    +materialized: table

# models/schema.yml
models:
  - name: foo
    deprecation_date: 1999-01-01 00:00:00.00+00:00
```

```sql
-- models/foo.sql
select 1 id

-- models/bar.sql
select * from {{ ref('foo') }}
```

Try running with 1.8:

```sh
$ dbt run --no-partial-parse

07:00:33  Running with dbt=1.8.7
07:00:33  Registered adapter: postgres=1.8.2
07:00:33  [WARNING]: Model foo has passed its deprecation date of 1999-01-01T00:00:00+00:00. This model should be disabled or removed.
07:00:33  [WARNING]: While compiling 'bar': Found a reference to foo, which was deprecated on '1999-01-01T00:00:00+00:00'. 
07:00:33  Found 2 models, 417 macros
07:00:33  
07:00:33  Concurrency: 4 threads (target='pg')
07:00:33  
07:00:33  1 of 2 START sql table model public.foo ........................................ [RUN]
07:00:33  1 of 2 OK created sql table model public.foo ................................... [SELECT 1 in 0.05s]
07:00:33  2 of 2 START sql table model public.bar ........................................ [RUN]
07:00:33  2 of 2 OK created sql table model public.bar ................................... [SELECT 1 in 0.02s]
07:00:33  
07:00:33  Finished running 2 table models in 0 hours 0 minutes and 0.22 seconds (0.22s).
07:00:33  
07:00:33  Completed successfully
07:00:33  
07:00:33  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```

Warning tells us that model `bar` is using a deprecated `foo`:

```sh
07:00:33  [WARNING]: While compiling 'bar': Found a reference to foo, which was deprecated on '1999-01-01T00:00:00+00:00'. 
```

Swap over to 1.9 pre and run again:

```sh
$ dbt run --no-partial-parse

07:01:31  Running with dbt=1.9.0-b2
07:01:31  Registered adapter: postgres=1.9.0-b1
07:01:31  [WARNING]: Model foo has passed its deprecation date of 1999-01-01T00:00:00+00:00. This model should be disabled or removed.
07:01:31  Found 2 models, 424 macros
07:01:31  
07:01:31  Concurrency: 4 threads (target='pg')
07:01:31  
07:01:32  1 of 2 START sql table model public.foo ........................................ [RUN]
07:01:32  1 of 2 OK created sql table model public.foo ................................... [SELECT 1 in 0.05s]
07:01:32  2 of 2 START sql table model public.bar ........................................ [RUN]
07:01:32  2 of 2 OK created sql table model public.bar ................................... [SELECT 1 in 0.02s]
07:01:32  
07:01:32  Finished running 2 table models in 0 hours 0 minutes and 0.22 seconds (0.22s).
07:01:32  
07:01:32  Completed successfully
07:01:32  
07:01:32  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```

Which is admittedly less helpful than before.

### Relevant log output

_No response_

### Environment

```markdown
- OS: macOS
- Python: 3.11.9
- dbt (working version): 1.8.7
- dbt (regression version): 1.9.0-b2
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

Since dbt Cloud versionless is on pre - then dbt Cloud also lost this warning message. Though you can go back to 1.7 to get this warning message back:

image

### PR DESCRIPTION
**Pull request by gshank**
Resolves #10833

### Problem

Due to some code changes we stopped reporting deprecation/upcoming deprecations for models referencing a model with a deprecation_date.

### Solution

Check models that refer to a model with a deprecation date.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me.
- [x] I have run this code in development, and it appears to resolve the stated issue.
- [x] This PR includes tests, or tests are not required or relevant for this PR.
- [x] This PR has no interface changes (e.g., macros, CLI, logs, JSON artifacts, config files, adapter interface, etc.) or this PR has already received feedback and approval from Product or DX.
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions.

### CODE REVIEW

**Review by ChenyuLInx — COMMENTED** [review]
Thanks for fixing this.
Given this is a regression, let's add a test to make sure this doesn't happen again.

**Comment by gshank** [comment]
There was a test. The problem was that none of the tests in the "tests/functional/deprecations" directory were being run, presumably because "deprecations" was some kind of reserved word for pytest. I ran into this before with the "build" directory, which I had to rename to "build_command".

**Review by peterallenwebb — APPROVED** [review]
Generally looks good, but it doesn't look like we have a test that would fail if this behavior were to regress again? If I'm right about that, can you please add one?

**Review by ChenyuLInx — APPROVED** [review]

**Comment by danlsn** [comment]
Hi there, this issue seems to have caused failures during parsing in our dbt cloud project using the "versionless" version.

```bash
06:43:39 Encountered an error:
'exposure.dap_dbt_da.research_plus_hdr_student_activity_report'
06:43:39 Traceback (most recent call last):
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/cli/requires.py", line 221, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/cli/requires.py", line 131, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/cli/requires.py", line 329, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/cli/requires.py", line 356, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/cli/requires.py", line 404, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/cli/requires.py", line 420, in wrapper
    setup_manifest(
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/cli/requires.py", line 469, in setup_manifest
    ctx.obj["manifest"] = parse_manifest(
                          ^^^^^^^^^^^^^^^
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/parser/manifest.py", line 2055, in parse_manifest
    manifest = ManifestLoader.get_full_manifest(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/parser/manifest.py", line 318, in get_full_manifest
    manifest = loader.load()
               ^^^^^^^^^^^^^
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/parser/manifest.py", line 521, in load
    self.check_for_model_deprecations()
  File "/venv/dbt-149263e0c5a7b047bf5cd7b44643df173f2f8287/lib/python3.11/site-packages/dbt/parser/manifest.py", line 606, in check_for_model_deprecations
    child_node = self.manifest.nodes[child_unique_id]
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'exposure.dap_dbt_da.research_plus_hdr_student_activity_report'
```

This error seems to occur when our exposures depend on versioned nodes. 

It seems like the child_unique_id of the exposure is being used to check for deprecated models. Not entirely sure.

Our platform team is reaching out to our contact at dbt-labs but I figured it would be worth raising here as this seems to have caused another regression and is currently blocking development for our production work.

Happy to provide more information if required.

**Pull request merged**
