### PR TITLE
When parsing 'all_sources' should be a list of unique dirs

### LINKED ISSUE #5120: [CT-524] [Bug] Issue co-locating models and seeds in the same directory
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I’m trying to set the seed-paths to my models folder exactly like described in the [docs](https://docs.getdbt.com/reference/project-configs/seed-paths#co-locate-your-models-and-seeds-in-the-models-directory) but getting an error:
```
  dbt found two resources with the name "raw_preprocessor_internal_accounts". Since these resources have the same name,
  dbt will be unable to find the correct resource when source("raw_preprocessor", "internal_accounts") is used. To fix this,
  change the name of one of these resources:
  - source.dbt.raw_preprocessor.internal_accounts (models/raw_preprocessor/internal_accounts.yml)
  - source.dbt.raw_preprocessor.internal_accounts (models/raw_preprocessor/internal_accounts.yml)
```

Seems like this should be relatively straightforward, not sure why it’s identifying the same source as a duplicate of itself. Relevant parts of the dbt_project.yml file:
```
name: dbt

config-version: 2

version: 1.0.0

require-dbt-version: '>=1.0.0,<1.1.0'

profile: dbt

docs-paths:
  - models
macro-paths:
  - macros
model-paths:
  - models
seed-paths:
  - models
test-paths:
  - tests

log-path: logs
packages-install-path: dbt_packages
target-path: target

clean-targets:
  - target
  - dbt_packages
```

### Expected Behavior

dbt is able to run (and compile) normally as it did before changing the `seed-paths`.

### Steps To Reproduce

_No response_

### Relevant log output

```shell
20:46:30  Running with dbt=1.0.5
20:46:30  Partial parse save file not found. Starting full parse.
20:46:33  No external sources selected
20:46:37  Encountered an error:
Compilation Error
  dbt found two resources with the name "raw_preprocessor_internal_accounts". Since these resources have the same name,
  dbt will be unable to find the correct resource when source("raw_preprocessor", "internal_accounts") is used. To fix this,
  change the name of one of these resources:
  - source.synctera_dbt.raw_preprocessor.internal_accounts (models/raw_preprocessor/internal_accounts.yml)
  - source.synctera_dbt.raw_preprocessor.internal_accounts (models/raw_preprocessor/internal_accounts.yml)
```
```


### Environment

```markdown
- OS: macOS 12.1
- Python: 3.1.
- dbt: 1.0.5
```

### What database are you using dbt with?

BigQuery

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by gshank**
resolves #5120

### Description

When two (or more) of the "-paths" settings point to the same directory, the "all_sources" method will return duplicate directory names, causing the attempt to parse the same files twice.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Review by nathaniel-may — APPROVED** [review]
nice and simple way to dedup the list. I do want to point out that it will change the order of the final list since `Set`s are unordered, so as long as that's not an issue this should be fine.

**Comment by emmyoop** [comment]
@leahwicz or @jtcohen6 should this be backported to `1.1.latest` for the next patch?

**Comment by leahwicz** [comment]
I would be ok backporting this since its a bug and it's a minimal change (most changes are involving test conversion)

**Comment by gshank** [comment]
Yeah, it's only a couple of lines. I'll backport without the tests.

**Pull request merged**
