### PR TITLE
Allow override of Column string and numeric type by classes inheritin…

### LINKED ISSUE #4603: [CT-78] [Bug] Adapters should be able to override string and numeric type of columns
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

String and numeric types are hardcoded in the base Column classes.

https://github.com/dbt-labs/dbt-core/blob/a588607ec6546de441812e215fbbf4e9ff20101b/core/dbt/adapters/base/column.py#L42-L44

When running dbt_utils.union_relations with the Trino adapter, following columns are generated based, hoever varying is not supported by Trino and the Trino adapter suppleis an overriding method for string_type.

```
cast("administratieve groep/iov code" as character varying(256)) as "administratieve groep/iov code"
```

image

### Expected Behavior

Adapters should be able to override the stirng and numeric types according to the specifications of the specific database.

### Steps To Reproduce

_No response_

### Relevant log output

_No response_

### Environment

```markdown
- OS: Macos
- Python: 3.9.10
- dbt: 1.0.0
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

Trino

### PR DESCRIPTION
**Pull request by mdesmet**
…g from the Column class

resolves #4603

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change

### CODE REVIEW

**Comment by mdesmet** [comment]
@gshank, @iknox-fa,

This is pretty important change for dbt-trino and potential other adapters to pickup the inherited methods instead of the core methods. can you have a look at this please?

**Comment by leahwicz** [comment]
Clsoing and reopening to get GitHub Checks to trigger.

**Comment by McKnight-42** [comment]
@mdesmet it seems we have one test failing  for for flake8

the error is : fix a indention issue as noted by `core/dbt/adapters/base/column.py:45:40: E127 continuation line over-indented for visual indent
 `

cause: seems like the name change from `column` to `self` is just making the indention a tad off.

suggested solution: A backspace or two should cause the flake8 tests to pass on Ln 45 

you should be able to double check this locally by running `tox` if you have any questions please reach out.

**Comment by McKnight-42** [comment]
@mdesmet sorry for the slow feedback, looks like we have tests passing which is great but now your branch is behind main by a commit or two, would you mind updating your local and repushing up so we can keep both in line with each other?

**Comment by mdesmet** [comment]
@McKnight-42 : Done!

**Review by McKnight-42 — APPROVED** [review]
Looks like a smart change to be able to overwrite types LGTM

**Comment by McKnight-42** [comment]
@mdesmet just a heads up a recent change in the black formatter we added caused a test to fail hopped on to make sure it would work. right before merging, thank you so much for working on this.

**Pull request merged**
