### PR TITLE
Fix untyped functions in `core/dbt/context/base.py`

### LINKED ISSUE #8394: [CT-2978] Fix untyped functions in context/base.py (mypy warning)
### Problem
When we hit a mypy error the console is flooded with mypy warnings as well.  Clean up the warning to improve developer experience. 

### Reproduction
Simply force a mypy error (change types) and the warnings will be generated.

### Relevant Output
```
core/dbt/context/base.py:188: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]

```

### PR DESCRIPTION
**Pull request by QMalcolm**
resolves #8394 

### Problem

We have a lot of untyped functions in `core/dbt/context/base.py` this means that
1. There is a lot of type checking that is not happening
2. When a type issue occurs in the file a bunch of `can't type check untyped functions` warnings appear

### Solution
ADD TYPES TO ALL THE THINGS 🎉 

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [X] I have run this code in development and it appears to resolve the stated issue  
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [X] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by QMalcolm** [comment]
I'm very confused on how the functions [contextmember](https://github.com/dbt-labs/dbt-core/blob/f94fdadde0f63ff1bccedcffb28e3b8e6a6441b4/core/dbt/context/base.py#L101) and [contextproperty](https://github.com/dbt-labs/dbt-core/blob/f94fdadde0f63ff1bccedcffb28e3b8e6a6441b4/core/dbt/context/base.py#L107) operate. The are function decorators, and in python function decorators are required to return a callable. However... in cases where the `value` passed into the decorator isn't a string, we return an object (`ContextMember`). Thus typing these two functions is neigh impossible because currently we have to state that one of the return types must be a bare `ContextMember` object, which then every invocation of the decorator complains about.

**Review by gshank — APPROVED** [review]

**Comment by McKnight-42** [comment]
Out of curiosity is this a different way of approaching the change we reverted here https://github.com/dbt-labs/dbt-core/pull/8306?

**Comment by QMalcolm** [comment]
> Out of curiosity is this a different way of approaching the change we reverted here #8306?

@McKnight-42 I'm not wholly sure, but I don't think so. I could absolutely be wrong about that though. My understanding of issue #8153 is that all numeric values were being forced into floats, and the solution (#8306) was to actually add an `Integer` object for creating integer numeric types. In this PR we're not adding or changing any functionality of the code itself (with the exception of [a613ef0](https://github.com/dbt-labs/dbt-core/pull/8525/commits/a613ef09dbd5de68c529acc2352c2a9ae8266883)). The primary focus of this PR is defining what the expected return type of a function should be. That way when we run mypy, it can properly check all of our typing. These function return type definitions are actually thrown away at run time and don't actually affect the operation of the code.

**Comment by McKnight-42** [comment]
ah makes sense thanks for clarification @QMalcolm

**Pull request merged**
