### PR TITLE
[Feature] Supports non half width alphanumeric for generic test

### LINKED ISSUE #8204: [CT-2867] [Feature] Supports non half width alphanumeric for generic test
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Double-byte characters in GenericTest should be displayed normally instead of "_".

### Describe alternatives you've considered

_No response_

### Who will this benefit?

Mainly Japanese users who use hiragana, katakana and kanji will be happy.
Also, this is great for other Asian users who use double-byte characters.

### Are you interested in contributing this feature?

_No response_

### Anything else?

I will try to solve it in the PR below.
https://github.com/dbt-labs/dbt-core/pull/8203

### PR DESCRIPTION
**Pull request by d-kaneshiro**
resolves #8204 

### Problem

Double-byte characters in GenericTest were displayed as "_".

#### Example

Double-byte character columns are displayed as "_" when `dbt test` is executed.
image

### Solution

Fixed an issue where double-byte characters were not displayed in GenericTest.

#### Example

All double-byte character columns are displayed when 'dbt test' is executed.
image

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by d-kaneshiro** [comment]
Added tests that include full-width hiragana, katakana, kanji, and half-width katakana columns.
All of these are working as intended.
CI test with GitHubActions has also been successful.
On the other hand, I have not verified the operation in environments other than Japan.

**Comment by gshank** [comment]
d-kaneshiro: Please remove the changes in core/dbt/task/runnable.py and change a line in core/dbt/parser/generic_test_builders.py from "clean_flat_args = [re.sub("[^0-9a-zA-Z_]+", "_", arg) for arg in flat_args]" to "clean_flat_args = [re.sub("\W+", "_", arg) for arg in flat_args]".

**Comment by gshank** [comment]
In addition, the tests/adapter set of tests is for tests that might be different in different adapters, and this functionality should not be different for different adapters, so please move the test to tests/functional/schema_tests.

**Comment by dbeatty10** [comment]
@d-kaneshiro there's three main things that we'd need to do for this PR:
1. Move the test to the `tests/functional/schema_tests` directory

1. Change a line in [core/dbt/parser/generic_test_builders.py](https://github.com/dbt-labs/dbt-core/blob/d597b80486ebb409685fafb23d972f5361ddf7fc/core/dbt/parser/generic_test_builders.py#L59) from this:
    ```python
    clean_flat_args = [re.sub("[^0-9a-zA-Z_]+", "", arg) for arg in flat_args]
    ```
    to this:
    ```python
    clean_flat_args = [re.sub("\W+", "", arg) for arg in flat_args]
    ```
1. Remove all of your changes in `core/dbt/task/runnable.py` (since it should be covered by the above change)

### Question

Would you be willing to make these changes? Or would you prefer us to make those changes within your branch?

**Comment by d-kaneshiro** [comment]
@dbeatty10 and @gshank 
Thank you for your advice!

@dbeatty10 
Feel free to implement these changes in my branch. (Because I can't think of a best practice for incorporating tests without breaking the existing configuration)
Please let me know after you make any changes. I'll check to see if it behaves as intended.

**Review by gshank — APPROVED** [review]
I do think that putting the functional test in the adapter zone isn't necessary, since this is core dbt functionality and not related to adapters. But it's not that big of an issue. I think we might be rearranging some of this soon anyway.

**Pull request merged**
