### PR TITLE
Allow greater mashumaro versions

### LINKED ISSUE #7295: [CT-2382] [Feature] allow a broader list of mashumaro versions.
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Allow more mashumaro versions.

### Describe alternatives you've considered

patching the requirment (setup.py) locally.

### Who will this benefit?

any packager.

### Are you interested in contributing this feature?

Sure.

### Anything else?

I'm in the process of packaging dbt for AUR (arch), so the requirment on mashumaro has to be the current one (system-wide install and no virtual env).

BTW, I have the same issue with pathspec, and hologram at least. (and the test is running fine).

### PR DESCRIPTION
**Pull request by benallard**
Current 3.5 is working fine.

resolves #7295

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by dbeatty10** [comment]
@gshank I briefly discussed this with @emmyoop offline. She suspects we have `mashumaro` pinned because upgrades have broken us in the past.

How do you think we should proceed?
1. Keep hard-pin
2. Expand upper-bound to highest version known to work
3. Something else

**Comment by gshank** [comment]
There have been multiple releases of mashumaro that have broken our code. Which means that even a range could be problematic because there could be a version in the range that won't work. We'd have to test with each version in the range...

I'm inclined to hard pin it.

@benallard Is there some reason you're requesting this? Are you using mashumaro outside of dbt?

**Comment by benallard** [comment]
See #7295

**Comment by jtcohen6** [comment]
For the reasons @gshank described above, we're going to keep `mashumaro` pinned to a specific release for now. However, I would be supportive of bumping the pinned version to the latest, if you want to update this PR to `mashumaro==3.6` (just released!).

**Comment by dbeatty10** [comment]
@benallard We require contributors to sign our [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScfOV7K4enYRHozrDRP6BBIXjOij-JDGca6WBTHyP_ANXSqlg/viewform) -- would you be willing to sign that so we can give you credit for this contribution?

**Comment by jtcohen6** [comment]
@benallard Just missing [a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry):
```
$ changie new
✔ Dependencies
Body: Bump mashumaro[msgpack] from 3.3.1 to 3.6
GitHub Username(s) (separated by a single space if multiple): benallard
GitHub Pull Request Number (separated by a single space if multiple): 7294
```

**Comment by benallard** [comment]
Yeah, changie ✅

**Pull request merged**
