### PR TITLE
Add model_sql helper to enable isolated unit testing

### PR DESCRIPTION
**Pull request by Zatte**
Improves Unit testing capabilities.

Enabler for: https://github.com/fishtown-analytics/dbt/issues/2354 
Discussed here: https://discourse.getdbt.com/t/testing-with-fixed-data-set/564/8  

Related: https://discourse.getdbt.com/t/state-of-testing-in-dbt/1778

### Description 
It didn't seem to be a good(relatively speaking) method for testing models in isolation. The best was introducing branching conditions in the model based on global settings which at most allowed for 1 test / model. 

This PR introduces a new helper-method `model_sql()` (the name is debatable, in previous discussions it was called `cte`)  which returns the compiled SQL code of a model but under a different context (allows one to overrides `var`/`ref`/`source` ). Models can be tested without changes outside test code and multiple tests can be build for the same model.

I think think approach is a cleaner approach to (unit) testing than what has been proposed so far.
1. Pure dbt (Jinja/SQL)
2. No need for custom macros.
3. No additional plugins (if this pr gets merged)
4. “Full" control per test
5. No changes/branching/flags required in production models (!)
6. Supports all data sizes. 

**Example use case:** 

**Model**
`models/addder.sql`
```sql
    SELECT 
      *,
      a+b + {{ var ("base", "0") }} AS sum
    FROM {{ ref('source_data') }}
```

**Test**
`tests/adder_0001.sql`
```sql
{% set model_to_test = model_sql(
    'model.adder',  {
      'var': {
        'base': '1'
      },
      'ref': {
        'source_data': 'mocked_source_data'
      }})
%}

WITH
mocked_source_data AS (
  SELECT
    *
  FROM
  -- bigquery construct; same effect as union all select ....
  UNNEST([
     struct(1 as a,  2 as b,  4 as expectedSum),
     struct(2 as a,  2 as b,  5 as expectedSum),
     struct(0 as a,  0 as b,  1 as expectedSum),
     struct(1 as a, -2 as b, 0 as expectedSum)
   ])
),

final AS (
  {{ model_to_test }}
)

-- Some SQL assertion based on the specific mocked data.
SELECT * FROM final WHERE sum != expectedSum
```

_I haven't been writing python for some 6 years and and this is the first time interacting the the DBT core, as such the PR is not  yet complete. I would like to get some feedback before investing more time into this. No point in "polishing a turd". 

If the maintainer(s) think it holds value i don't mind ticking all the boxes below (or hand it over to someone else)_

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by Zatte** [comment]
@drewbanin I did sign the CLA some time ago but the PR seems stuck in this state. Anything you can help with?

**Comment by jtcohen6** [comment]
@cla-bot re-check

**Comment by jtcohen6** [comment]
@cla-bot check

**Comment by jtcohen6** [comment]
@Zatte Apologies, the delay here is completely on me. I'm playing catch-up this week; I'm going to do my best to take a detailed look and give you feedback soon.

**Comment by Zatte** [comment]
@jtcohen6 : Just a monthly ping, hoping this is not forgotten until the end of times :)

**Pull request closed without merging**
