### PR TITLE
[CT-2343] [Bug] snapshot with custom datatypes breaks when source table is regenerated

### PR DESCRIPTION
**Pull request by benorourke**
Resolves dbt-labs/dbt-postgres#13 

> [!IMPORTANT]  
> The contents of this PR should be compared with https://github.com/dbt-labs/dbt-core/pull/9433 since they both touch on the same code and could easily overwrite each other. Ideally, both of them will functional tests so that one doesn't undo the other by accident.

### Description

The macro [postgres__get_columns_in_relation](https://github.com/dbt-labs/dbt-core/blob/87e25e8692197c093e9be2c0df5fe38dea48eec5/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L59), which is called when the snapshot checks for any column changes, selects data_type from the information_schema. For any UDT this will return USER-DEFINED. We can instead conditionally select udt_name to get the name of the enum.

This pull request modifies the macro postgres__get_columns_in_relation to resolve udt names along with their schema, resulting in a successful snapshot build for source tables containing a UDT.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by McKnight-42** [comment]
closing and reopening to try and trigger tests

**Review by McKnight-42 — APPROVED** [review]

**Review by McKnight-42 — CHANGES_REQUESTED** [review]
@benorourke Thank you for implementing this fix. It looks like this is coming along fantastic. I think the only thing blocking this would be to possibly build out a small functional test styled after the examples mentioned in #7248 

I would suggest creating the test file in the `tests/functional` zone as it is postgres specific.

if there is anything I can do to help out please feel free to reach out.

**Comment by dbeatty10** [comment]
> the only thing blocking this would be to possibly build out a small functional test

Good call @McKnight-42 🧠

If we merge this without adding a functional test, then it could easily be un-done by a different PR like https://github.com/dbt-labs/dbt-core/pull/9433.

So we'll definitely want a functional test before merging this.

Here's manual test that I did: https://github.com/dbt-labs/dbt-core/issues/7248#issuecomment-1522188017 -- not sure how hard it would be to convert it to a functional test.

**Comment by dbeatty10** [comment]
Thanks for taking the time to open this PR @benorourke! Since opening, we've [decoupled dbt Adapters from dbt Core](https://github.com/dbt-labs/dbt-core/discussions/9171), and this code now lives in a separate repo: [dbt-postgres](https://github.com/dbt-labs/dbt-postgres).

A consequence of the decoupling is that PR can't be merged anymore as is, so we're closing it. For more context see [#9171](https://github.com/dbt-labs/dbt-core/discussions/9171).

The linked issue has already been transferred. Please don't hesitate to re-open your proposed code changes within this PR in the dbt-postgres repo.

**Pull request closed without merging**
