### PR TITLE
[CT-2776] [Feature] Enable-post-parse-population-of-dbt-custom-env

### PR DESCRIPTION
**Pull request by gem7318**
### Description

Addresses #8010.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
@gem7318 Cool to see the PR! I'm not strictly opposed to this from a product/UX perspective. Do you mind opening a quick issue to outline the use case? (You've written some of it above, and a bit more in our shared slack thread)

**Comment by gem7318** [comment]
@dbt-labs/oss-maintainers 

Please let me know if anything's unclear here.

**Review by QMalcolm — APPROVED** [review]
First off, thank you for doing this work @gem7318! This looks great, and we should get this in 🙂 

The second thing is, in a perfect world this should go away some time in the future. Basically, one shouldn't have to alter the environment variables mid run to get the desired results. This seems indicative of larger structural issues we need to address. However, I can make no guarantees of when we'll address the structural changes necessary to support the desired functionality without altering the environment variables mid run. Thus we should absolutely move forward with allowing this.

**Comment by QMalcolm** [comment]
@jem7318 It looks like there are two remanining github actions that are required to be run before we can merge this. I believe main needs to be merged into this branch so that this branch has the required github actions (they were recent additions to our github workflow, and are now required).

**Comment by QMalcolm** [comment]
@gem7318 It looks like there are two remaining github actions that are required to be run before we can merge this. I believe main needs to be merged into this branch so that this branch has the required github actions (they were recent additions to our github workflow, and are now required).

**Comment by gem7318** [comment]
> @gem7318 It looks like there are two remaining github actions that are required to be run before we can merge this. I believe main needs to be merged into this branch so that this branch has the required github actions (they were recent additions to our github workflow, and are now required).

@QMalcolm I just synced my fork and pulled `main`/rebased out of habit - let me know if this isn't what we were looking for to get checks to fire again (looks good to me though).

image

**Comment by QMalcolm** [comment]
A -0.05% in test coverage feels acceptable. Gonna use my judgement and move forward, merging 🙂

**Pull request merged**
