### PR TITLE
Add metadata env method to provider context

### LINKED ISSUE #5522: [CT-896] [Feature] Add Jinja function which returns all `DBT_ENV_CUSTOM_ENV_ ` and `DBT_CLOUD_` environment variables
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Right now, you have to know which environment variables might be set in order to get the values for them using the `env_var` function. For the dbt_artifacts package (and other like it) it would be helpful to be able to call a single function which returns all `DBT_ENV_CUSTOM_ENV_` and `DBT_CLOUD_` environment variables, in the same way they are all present in the manifest.json's metadata env field.

### Describe alternatives you've considered

Asking users to configure variables to describe their in-use env vars

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jared-rimmer**
resolves #5522

### Description

- Added the method `dbt_metadata_envs` which is a wrapper for the `get_metadata_env` method which is imported from `dbt.contracts` as it already contained the required functionality.
- Also includes small refactoring of the tests to add two helper functions for parsing json logs and find the result needed in the parsed logs. This was repeated in another test so decided to split it out to avoid repetition. 

### Open Question

- The requirements on the initial issue mention the DBT_CLOUD variables which are detailed [here](https://docs.getdbt.com/docs/dbt-cloud/using-dbt-cloud/cloud-environment-variables). Are you happy for me to extend the `dbt_metadata_envs` method to search for the prefix DBT_CLOUD_ as well?

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [X] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [X] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [X] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by gshank** [comment]
You need to run "changie new" to create a changelog entry. See [CONTRIBUTING.md](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

**Comment by smitsrr** [comment]
@gshank - any other changes required on this PR?

**Comment by gshank** [comment]
I think if you merge main into your branch, this is probably ready to go. There were some metrics attribute name changes so tests are failing.

**Comment by jared-rimmer** [comment]
All done @gshank

**Pull request merged**
