### PR TITLE
dbt build performance fix

### PR DESCRIPTION
**Pull request by china-cse**
introduced trim graph to speed up dbt build execution

resolves https://github.com/dbt-labs/dbt-core/issues/6073

### Description
it resolves the performance issue of **dbt build** with more than 2K nodes in project. its been tested in local environment, and its working as expected.. all details provided in https://github.com/dbt-labs/dbt-core/issues/6073

Have worked on below approach, this takes less time in finding nodes.. and tested with 10K nodes.. seems its giving faster results.

this solution requires additional function (lets say "trim_graph()") for scalability purpose which main purpose is to remove unnecessary nodes/paths except direct paths
all details explained in https://github.com/dbt-labs/dbt-core/issues/6073
### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
@china-cse Thanks for opening, and for the ongoing work on this!

Are you able to sign our CLA? So long as you can do that, one of the engineers from our team can take a look at the proposed changes, and determine if this PR is merge-ready.

**Comment by china-cse** [comment]
Hi @jtcohen6 

I'm unable to sign CLA using details link.. it takes me to https://s3.amazonaws.com/cla-bot-logs/ page.. but nothing to fill in. Where I have to sign it?

**Comment by china-cse** [comment]
Hi @jtcohen6 

sorry, please ignore previous msg.. was able to find the link to google forms from cla-bot message above.. filled in all info

**Comment by jtcohen6** [comment]
@cla-bot check

**Comment by china-cse** [comment]
Team, please let me know if anything required from my side..

**Review by stu-k — COMMENTED** [review]
I am unfamiliar with our methods of graph traversal, so I will leave this for other members on my team to approve or request changes. Just a small note about commented out code!

**Comment by china-cse** [comment]
DBT Team,

Any update on review of this pull request. It’s been a while and no status updated. Please confirm. If all good, I can just remove comments as mentioned by @stu-k and push the changes.

thanks

**Comment by jtcohen6** [comment]
@china-cse Sorry for the delay. We've been discussing this one internally, and we want to make sure we're doing a thorough job of benchmarking & testing. See this issue for some proposed next steps: https://github.com/dbt-labs/dbt-core/issues/6562

**Comment by jtcohen6** [comment]
@china-cse After taking a closer look, and testing with some sample projects, we did not see a performance improvement associated with the changes in this PR. In some cases, we saw degraded performance.

Those investigations did yield some performance speedups, which we've since merged in:
- https://github.com/dbt-labs/dbt-core/pull/6694
- https://github.com/dbt-labs/dbt-core/pull/6720

I'm going to close this PR for now. That said, it sounds like you were able to verify locally that these changes led to a speedup as expected:
> Have worked on below approach, this takes less time in finding nodes.. and tested with 10K nodes.. seems its giving faster results.

If you'd be able to share some detailed timing information with us, or even a version of your project (anonymized if need be) so that we could dig deeper in on our end, we might reopen the PR.

**Pull request closed without merging**
