### PR TITLE
Support disabling unit tests

### PR DESCRIPTION
**Pull request by tsturge**
Support config: disabled for unit tests. (#9109)

Also, when a model is disabled, disable the corresponding unit tests automatically. (#10540)

### Problem

config:
   enabled: false

### Solution

Check for the config: enabled variable while parsing the unit test. If it is set to false, mark the unit test as disabled.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me.
- [x] I have run this code in development, and it appears to resolve the stated issue.
- [x] This PR includes tests, or tests are not required or relevant for this PR.
- [x] This PR has no interface changes (e.g., macros, CLI, logs, JSON artifacts, config files, adapter interface, etc.) or this PR has already received feedback and approval from Product or DX.
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions.

### CODE REVIEW

**Comment by devmessias** [comment]
I like this. Especially because the unit tests are now broken when we have ctx like vars inside the model. The way I was handling this was by commenting them out.

**Review by gshank — APPROVED** [review]

**Comment by maxmarcon** [comment]
Hi! I was eagerly waiting for this to be released. I saw that this PR was merged 3 weeks ago. A new dbt-core version (1.8.9) was released one week ago but this feature doesn't seem to work there yet. This unit test:

```yaml
version: 2

unit_tests:
  - name: consolidate_gmv_currencies
    config: 
      enabled: false 
    model: validate_consolidate_gmv_currencies
```

gets still listed by `dbt list`

Am I missing something? Thanks

**Comment by davidbooke4** [comment]
> Hi! I was eagerly waiting for this to be released. I saw that this PR was merged 3 weeks ago. A new dbt-core version (1.8.9) was released one week ago but this feature doesn't seem to work there yet. This unit test:
> 
> ```yaml
> version: 2
> 
> unit_tests:
>   - name: consolidate_gmv_currencies
>     config: 
>       enabled: false 
>     model: validate_consolidate_gmv_currencies
> ```
> 
> gets still listed by `dbt list`
> 
> Am I missing something? Thanks

@maxmarcon the changes in this PR weren't included in 1.8.9, but they are included in 1.9.0. I've tested out disabling them as you have above, and it's working for me.

**Comment by davidbooke4** [comment]
While explicitly disabling a unit test using the below code is working:
```
version: 2

unit_tests:
  - name: consolidate_gmv_currencies
    config: 
      enabled: false 
    model: validate_consolidate_gmv_currencies
```

I'm still getting parsing errors when a model is disabled and a unit test is not explicitly disabled:
```
Parsing Error
  Unable to find model 'disabled_model' for unit test 'unit_test_for_disabled_model' in ...
```
Whether I have the model disabled using conditional logic such as `config(enabled=var('model_enabled', false)) != false` or `config(enabled = false)` doesn't make a difference. 

It seems like the unit test should be disabled in this situation based on the changes made in `core/dbt/parser/unit_tests.py` in this PR. It looks like the unit tests added in this PR are testing for when unit tests are disabled and not when models are disabled, but I could be wrong about that.

I'm testing this out on dbt-core v1.9.0 and dbt-bigquery v1.9.0. Please let me know if I'm doing something wrong - thanks!

**Comment by srggrs** [comment]
Hi guys do you plan to backport this into v1.8 minor release, we are currently blocked on upgrading to v1.9 as our other OSS parts won't work with v1.9. Thanks 🙏🏼

**Pull request merged**
