### PR TITLE
Renaming Attributes In Metric Spec

### LINKED ISSUE #5774: [Feature] Update Metric Spec With Clearer Names
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

_Technically a duplicate of this issue https://github.com/dbt-labs/dbt-core/issues/4325_

Right now, we have two fields within the metric spec whose names don't perfectly match what they are trying to convey.
- `sql` : this attribute represents the sql expression that will be aggregated. It can be a simple field (user_id) or more complicated (case when x > y then x else y end)
- `type` : this attribute represents the calculation / aggregation method that we are performing on the expression. 

### Proposed Change

As such, I propose the following changes:
- Renaming `type` to `calculation_method`. 
  - **_Why calculation method and not aggregation method?_** This is because we do have some metrics that aren't aggregations. Specifically expression/derived metrics. Calculation method keeps the door open to other metric types in the future that also aren't technically aggregations
- Renaming `sql` to `expression`
  - Alternatively we could call this `measure` - this would build off the prior art of a lot of BI tools.
- Renaming `expression` type metrics to `derived` metrics
  - This was the top suggestion for name by the community. I have no strong opinions on this one so I will bow to the will of the community
 
<details>
<summary> Old format </summary>

```yml
version: 2 
metrics:
  - name: base_average_metric
    type: average
    sql: discount_total

    model: ref('fact_orders')
    label: Total Discount ($)
    timestamp: order_date
    time_grains: [day, week, month, all_time]
    dimensions:
      - had_discount
      - order_country
```

</details>

<details>
<summary> New format </summary>

```yml
version: 2 
metrics:
  - name: base_average_metric
    calculation_method: average
    expression: discount_total

    model: ref('fact_orders')
    label: Total Discount ($)
    timestamp: order_date
    time_grains: [day, week, month, all_time]
    dimensions:
      - had_discount
      - order_country

```

</details>

Let me know what y'all think!

### Describe alternatives you've considered

Not changing this.

### Who will this benefit?

Anyone who uses metrics!

### Are you interested in contributing this feature?

Yep! Already scoping it out in a PR

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by callum-mcdata**
resolves #5774 

### Description

- Renaming `sql` to `expression`
- Renaming `type` to `calculation_method`
- Renaming `expression` type metrics to `derived`

### Checklist

- [X] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [X] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [X] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by callum-mcdata** [comment]
Interestingly I am getting this error `Could not render {{metric('collective_tenure')}} / {{metric('number_of_people')}} : 'metric' is undefined` which seems to suggest that changing the name of the `sql` field to `expression` broke the ability to reference `metric` in a metric sql field. I've tried searching through the codebase but can't seem to figure out why

**Comment by callum-mcdata** [comment]
After some helpful pointers from Jerco, it looks like `schema_renderer.py` is where my issue was. It was specifically looking for the `sql` field in the metrics spec in order to render the jinja in that field. Updated and seems to have fixed that issue!

**Comment by callum-mcdata** [comment]
Holding off until 9/8 to give the community time to respond.

**Comment by callum-mcdata** [comment]
This PR is ready for review/merge now! The community had no 🔴 flag alarms on the naming so we move forward

**Review by gshank — APPROVED** [review]
Looks good!  I do think that these name changes are an improvement.

**Comment by callum-mcdata** [comment]
Perfect, thank you for the review @gshank ! I don't have merge permissions though so would you mind merging it if we've got the reviews we need? Otherwise I can wait for Nathaniel or Colin if we need to get their go ahead as well

**Pull request merged**
