### PR TITLE
Generate static index html documentation

### LINKED ISSUE #8614: [CT-3105] [Feature] Generate static documentation (static_index.html)
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Static webpages (all resources bundled within them) are very useful -- you can inspect them directly without starting a webbrowser, and they can be served by e.g. object stores.

There is a long-standing feature request in dbt-docs for this [here](https://github.com/dbt-labs/dbt-docs/issues/53). I have created a PR within dbt-docs and will be creating a PR within dbt-core based on its output.

### Describe alternatives you've considered

External tools (as described in the [dbt-docs issue](https://github.com/dbt-labs/dbt-docs/issues/53)) can be created, but this is ugly and a hack.

In terms of doing this properly (within dbt itself), I considered a few other alternatives -- delayed webpack, bundling within Python (dbt-core), but all of these are both very complicated, different to how things are working now.

### Who will this benefit?

See the history of [dbt-docs issue](https://github.com/dbt-labs/dbt-docs/issues/53) for some of the benefits.

One specific example is hosting in Google Cloud Storage buckets -- a static index.html can be directly shared using GCP permissions, while one that retrieves manifest.json and catalog.json cannot. The bucket must either be public (usually undesirable) or exposed through a webserver (more complex).

### Are you interested in contributing this feature?

Yes. PR will be attached.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mescanne**
resolves #8614  

### Problem

Generated documentation that depends on external manifest.json and catalog.json must be hosted by a webserver. There are circumstances (such as in a local filesystem or in an object storage) where this creates an extra step for inspecting the documentation that isn't necessary with a static index.html.

### Solution

By upgrading the index.html (see [dbt-docs PR#465](https://github.com/dbt-labs/dbt-docs/pull/465)), it allows for generation of static index.html through search-and-replace of the manifest.json and catalog.json data within the index.html.

This is backwards compatible (and indeed produces static_index.html as output) and is a technique that can be easily used across new outputs if the documentation is enhanced in the future.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by mescanne** [comment]
Note -- I unchecked the "has no interface changes" as it does have a new command line option (--static) which enables some additional behaviour.

I'd be happy to add some text to the documentation i.e. [public](https://docs.getdbt.com/reference/commands/cmd-docs), [markdown](https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/reference/commands/cmd-docs.md). I assume that should be done at a later stage.

**Comment by mescanne** [comment]
Hello - I'm glad someone is assigned. Please let me know if there's anything I can do to help this along.

Thanks.

**Comment by jtcohen6** [comment]
@mescanne Thanks so much for opening these PRs! It's one thing to weigh in on a highly upvoted issue; it's another to push up the code to make it happen.

@QMalcolm and I have taken a first look together. We both appreciate the care you've taken to make this an additive change, with minimal risk for existing functionality. Unfortunately, our planned time to look again together on Friday was interrupted by our need to respond to an emergent regression in v1.6.4 (https://github.com/dbt-labs/dbt-core/issues/8749).

Overall, I am supportive of this change. We're coming close to the wire for the things we _must_ get in for dbt Core v1.7, in support of our top-level initiatives this year (Semantic Layer and Model Governance / Multi-project), so we likely won't be able to include this change in 1.7 — but I'd be happy to have it in for the following release.

**Comment by mescanne** [comment]
@jtcohen6 Thanks for the response. I've struggled with work arounds to this for quite some time, so if it's in the 1.8 mainline that's fine, too.

I'm also happy to engage in a discussion about the approach.

**Review by QMalcolm — APPROVED** [review]
@mescanne Thank you for doing this work! Sorry about the lag time in getting this approved, I adopted a cat and then immediately got sick 🙃 I've been through the code and it looks fantastic! Additionally, I've tried the changes locally, and I didn't run into any unexpected situations. Thanks again, we'll get it shipped 🚀 

Also cat tax: 
IMG_3839

**Pull request merged**
