### PR TITLE
Add quotes to usernames when revoking and granting table permissions

### LINKED ISSUE #6444: [Bug] Grants fails to correctly quote username when revoking
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

As part of the new grants feature, https://docs.getdbt.com/reference/resource-configs/grants dbt will attempt to revoke users not part of the grant before reapplying users listed in the grant. 
DBT does this (at least in the Redshift adaptor ) by pulling the table permissions and explicitly looping through every user then using a revoke command like 
revoke select on "database"."schema"."table" from user1, user2 ;
The user is not quoted so a user like user.name will fail with 
syntax error at or near "."
  LINE 2: ...user1, user.name, user2...

I am fairly certain the macro in https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/adapters/apply_grants.sql line 82 just needs some quotes

### Expected Behavior

the revoke command should quote users
revoke select on "database"."schema"."table" from "user1", "user2" ;

### Steps To Reproduce

Create a user with a period in the name for example in Redshift 
create user "first.last";

Create a simple dbt incremental model and user the grant syntax to give permission to that table within dbt.

Run DBT twice (on the first run the revoke macro is not run as the table is new)

### Relevant log output

_No response_

### Environment

```markdown
- OS:Ubuntu 20.04
- Python: 3.8.10 
- dbt: 1.3.1
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by barton996**
resolves dbt-labs/dbt-adapters#156
resolves dbt-labs/dbt-postgres#55

### Problem
For models with grants, where the corresponding table is not new (model has been run before), dbt revokes all grants on this table by looping through all users with table permissions.

The macro currently does not surround the user names that it reads from the table permissions with quotes, meaning that revoke statements on users with usernames like first.last will fail.

This is problematic when granting to a user GROUP, as you cannot control what is returned by the table permissions query using your grant yaml config e.g. grants: select: ["GROUP developers"].

### Solution
apply_grants.sql jinja template is updated so that usernames are surrounded with adapter.quote() character when granting and revoking.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

### CODE REVIEW

**Comment by barton996** [comment]
@mikealfare @dbeatty10

**Review by mikealfare — DISMISSED** [review]

**Comment by graciegoheen** [comment]
One thing to callout here - I believe this will make usernames case-sensitive, which is technically not backwards compatible.

**Comment by dbeatty10** [comment]
> One thing to callout here - I believe this will make usernames case-sensitive, which is technically not backwards compatible.

Good callout @graciegoheen. I think we should finish refining the behavior within https://github.com/dbt-labs/dbt-core/issues/8751 before merging this.

Specifically, https://github.com/dbt-labs/dbt-core/issues/8751#issuecomment-1747199588 mentions the following:

> One thing for us to consider is if we can/should add a `quote_grants` config for grants (or something else similar to [`quote_columns`](https://docs.getdbt.com/reference/resource-configs/quote_columns)). If we add some kind of quoting-related config, hopefully it would fit together with https://github.com/dbt-labs/dbt-core/issues/2986.

**Review by dbeatty10 — CHANGES_REQUESTED** [review]
@barton996 and @graciegoheen adding a blocking review here to prevent an accidental merge until we decide if we can/should make this backwards-compatible or not. See discussion [here](https://github.com/dbt-labs/dbt-core/pull/8809#issuecomment-1756305771).

**Comment by dbeatty10** [comment]
Thanks for taking the time to open this PR @barton996! Since opening, we've [decoupled dbt Adapters from dbt Core](https://github.com/dbt-labs/dbt-core/discussions/9171), and this code now lives in a separate repo: [dbt-adapters](https://github.com/dbt-labs/dbt-adapters).

A consequence of the decoupling is that PR can't be merged anymore as is, so we're closing it. For more context see [#9171](https://github.com/dbt-labs/dbt-core/discussions/9171).

The linked issue has already been transferred. Please don't hesitate to re-open your proposed code changes within this PR in the dbt-adapters repo.

**Pull request closed without merging**
