### PR TITLE
Change from unittest to pytest for manifestLoader

### PR DESCRIPTION
**Pull request by ChenyuLInx**
#9961
converted `test_parse_manfiest.py` from unit test to pytest and moved it around.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x]  I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

### CODE REVIEW

**Comment by ChenyuLInx** [comment]
@QMalcolm @emmyoop any suggestions on creating issues for these changes/not? I guess we can maybe have one issue for reorganize and all link to it?

**Comment by QMalcolm** [comment]
Here is the one big issue: https://github.com/dbt-labs/dbt-core/issues/9961

**Comment by QMalcolm** [comment]
Additionally I think we can skip the changelog for these changes as long as all the changes are contained to `/tests`. Changelog is really for the distributed source code I believe, and thus don't make much sense for this kind of work.

**Review by QMalcolm — CHANGES_REQUESTED** [review]
Looks good, we should drop the changelog though and fix the merge conflicts

**Review by QMalcolm — APPROVED** [review]

**Pull request merged**
