### PR TITLE
Feature/incremental predicate support

### PR DESCRIPTION
**Pull request by dave-connors-3**
resolves [#3923](https://github.com/dbt-labs/dbt/issues/3293)

### Description

This PR adds an optional configuration to incremental models that allows the user to supply an arbitrary filter expression to merge/delete statements to reduce the amount of data scanned while performing those operations. 

V1 of this logic allows the user to pass a dictionary to the new `incremental predicates` config to supply a column and expression to evaluate at runtime. The dictionary format allows proper table aliasing in these statements. 

Example:
```
{{
    config(
        materialized='incremental',
        unique_key = 'customerorderid',
        incremental_predicates = [{
            'source_col' : 'customerorderid',
            'expression' : '> 1'
        }]
        
    )
}}
```

TODO:
- [ ] consolidate `predicates` and `incremental_predicates` (if possible!)
- [ ] add integration tests
- [ ] incorporate macro formatting standards

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [ ] I have run this code in development and it appears to resolve the stated issue
 - [ ] This PR includes tests, or tests are not required/relevant for this PR
 - [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jtcohen6** [comment]
Nice work so far @dave-connors-3!

As discussed in our hangout:
- I'm on board the dictionary form of `incremental_predicates`, where users supply `column` + `expression`
- Let's combine `predicates` + `incremental_predicates`, so that each `get_x_sql` macro takes a single argument (`predicates`) and says where to put 'em
- Earlier materialization / macro logic should be responsible for merging user-supplied custom predicates with "built-in" strategy-specific predicates, such as the `unique_key` match expression for `merge`

**Comment by rumbin** [comment]
Any progress on this?
This feature would be very helpful for us.

**Comment by leahwicz** [comment]
@dave-connors-3 are you waiting for a review from us here? If so I can get some 👀 on this

**Comment by dave-connors-3** [comment]
@leahwicz -- unfortunately no! I ran out of steam on this a while back and didn't quite get the Bigquery portion over the line. I think it's best to close out this PR and start fresh -- definitely would like to take another run at this!

**Pull request closed without merging**
