### PR TITLE
fix(core): relax pathspec upper bound version limitation

### LINKED ISSUE #9372: [CT-3546] Remove restrictive `pathspec` version depencency (upper bound)
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently [pathspec>=0.9,<0.12](https://github.com/dbt-labs/dbt-core/blob/main/core/setup.py#L68) which conflicts with latest version of pathspec (0.12.1). I can't find any reason specifically for <0.12. It seems to be consequence of dependebot upgrading more restrictive pathspec~=0.9 [here](https://github.com/dbt-labs/dbt-core/pull/5917) and then later [here](https://github.com/dbt-labs/dbt-core/pull/6737)

### Expected Behavior

I can't find any reason to restrict pathspec <0.12. I couldn't find any major change that can break anything related to this package in [pathspec change log](https://github.com/cpburnz/python-pathspec/blob/v0.12.1/CHANGES.rst).

### Steps To Reproduce

1. `pip install dbt-core==1.7.4 -c <(echo "pathspec==0.12.1")`

### Relevant log output

```shell
The conflict is caused by:
    dbt-core 1.7.4 depends on pathspec<0.12 and >=0.9
    The user requested (constraint) pathspec==0.12.1
```

### Environment

```markdown
- OS: NA
- Python: >3.8
- dbt: >1.2.6
```

### Which database adapter are you using with dbt?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rzjfr**
resolves #9372

### Problem

Starting from dbt-core 1.2.6 this dependency has been added: [pathspec>=0.9,<0.12](https://github.com/dbt-labs/dbt-core/blob/main/core/setup.py#L68) which conflicts with latest version of pathspec (0.12.1). I can't find any reason specifically for <0.12. It seems to be consequence of dependebot upgrading more restrictive pathspec~=0.9 [here](https://github.com/dbt-labs/dbt-core/pull/5917) and then later [here](https://github.com/dbt-labs/dbt-core/pull/6737)

### Solution

I can't find any reason to restrict pathspec <0.12. I couldn't find any major change that can break anything related to this package in [pathspec change log](https://github.com/cpburnz/python-pathspec/blob/v0.12.1/CHANGES.rst). Here I just removed the upper bound. If we want to be for some reason very conservative about this particular package we can change it either to <0.13 or <1.
 

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

### CODE REVIEW

**Comment by dbeatty10** [comment]
Thanks for opening @rzjfr

Could you do the following?
1. Sign the Contributor License Agreement (CLA)
1. Add a changelog entry via `changie new` (so that it will show in the changelog under the [Dependencies](https://github.com/dbt-labs/dbt-core/blob/1.7.latest/CHANGELOG.md#dependencies) section)

**Comment by rzjfr** [comment]
> Thanks for opening @rzjfr
> 
> Could you do the following?
> 
>     1. Sign the Contributor License Agreement (CLA)
> 
>     2. Add a changelog entry via `changie new` (so that it will show in the changelog under the [Dependencies](https://github.com/dbt-labs/dbt-core/blob/1.7.latest/CHANGELOG.md?rgh-link-date=2024-01-16T22%3A37%3A04Z#dependencies) section)

Thanks for the review @dbeatty10, I did both :+1: 

While merging main back to the PR I realised [this commit](https://github.com/dbt-labs/dbt-core/commit/73a0dc6d147923573faaa0e13d51995b2d2caddd) which was arguing for keeping the upper bound as it's in major-version-0, so I just upgraded 0.12 to 0.13 while I was resolving the conflict.
I've already checked the [changelog of 0.12](https://github.com/cpburnz/python-pathspec/blob/v0.12.1/CHANGES.rst) there should be no breaking change.

What do you think?

**Review by ChenyuLInx — APPROVED** [review]
@rzjfr Thanks for contributing! This looks good to me!
Do you mind push a commit to get the code quality check passing? Then I can merge.

**Comment by rzjfr** [comment]
> @rzjfr Thanks for contributing! This looks good to me! Do you mind push a commit to get the code quality check passing? Then I can merge.

Hi @ChenyuLInx ,
Thanks for checking the PR,

Sorry for that, It must have been failing when I created my branch and I didn't realize.
I merged main back again as this [PR](https://github.com/dbt-labs/dbt-core/pull/9377) seem to have addressed the issue.

**Comment by safwank** [comment]
Any chance this this will be merged soon?

**Comment by jerry153fish** [comment]
+1 We will need this to unblock our process. Thanks very much.

**Comment by safwank** [comment]
@dbeatty10 @ChenyuLInx Sorry to be a pain, but our pipelines have been broken for a couple of weeks now, and we really need this PR merged. From the looks of it, it seems to be a very low-risk PR. Is there anything I can do to expedite it?

**Review by pacha — APPROVED** [review]

**Pull request merged**
