### PR TITLE
fix retry logic failures

### LINKED ISSUE #5023: [CT-473] [Bug] dbt deps still can fail with `'NoneType' object is not subscriptable`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It appears that there is still an exception that the current code is not catching on v1.0.5-rc2 -- this one is new!

```
Traceback (most recent call last):
  File "/usr/src/app/sinter/clients/dbt.py", line 1333, in call
    dbt_main.handle(command + extra_args)
  File "/usr/local/lib/python3.8/dist-packages/dbt/main.py", line 152, in handle
    res, success = handle_and_check(args)
  File "/usr/local/lib/python3.8/dist-packages/dbt/main.py", line 192, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/lib/python3.8/dist-packages/dbt/main.py", line 246, in run_from_args
    results = task.run()
  File "/usr/local/lib/python3.8/dist-packages/dbt/task/deps.py", line 56, in run
    final_deps = resolve_packages(packages, self.config)
  File "/usr/local/lib/python3.8/dist-packages/dbt/deps/resolver.py", line 135, in resolve_packages
    target = final[package].resolved().fetch_metadata(config, renderer)
  File "/usr/local/lib/python3.8/dist-packages/dbt/deps/registry.py", line 150, in resolved
    available = registry.get_available_versions(self.package)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/registry.py", line 131, in get_available_versions
    response = package(package_name)
  File "/usr/local/lib/python3.8/dist-packages/dbt/clients/registry.py", line 120, in package
    return response["versions"]
TypeError: 'NoneType' object is not subscriptable
```

so something else is sneaking through.

### Expected Behavior

The root cause of this error is caught, logged, and the download retried.

### Steps To Reproduce

_No response_

### Relevant log output

_No response_

### Environment

```markdown
- dbt: 1.0.5-rc2 (dbt Cloud)
```

### What database are you using dbt with?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by emmyoop**
resolves #5023

### Description

While the retry logic got fixed with the last iteration, there has always been a bug that the retry logic would fail since we were never actually _returning_ the result of the retry.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] ~~I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose)~~, or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Review by iknox-fa — APPROVED** [review]
This all looks great to me so I'm giving it the 👍, but why do we have two different copies of the same tests in differently named files?

**Review by gshank — APPROVED** [review]
Hope this does it!

**Comment by emmyoop** [comment]
@iknox-fa greta catch.  I renamed the file but apparently just created a new one.  Don't know how that happened.  Will clean it up before I merge.

**Comment by emmyoop** [comment]
backported to `1.0.latest` manually with #5147

**Pull request merged**
