### PR TITLE
Added columnar option to PostgreSQL table configuration

### LINKED ISSUE #6052: [CT-1335] [Feature] Add support for columnar tables for the PostgreSQL table materialization
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Make it configurable to add a configuration parameter with columnar that is a boolean, that

### Describe alternatives you've considered

Posthook is possible, however data then already is written in a row-orientation in the table.

### Who will this benefit?

Anyone using Citus Columnar extension for analytic or DW workloads:
- Compression
- Doesn't read unnecessary columns
- Efficient VACUUM

### Are you interested in contributing this feature?

Yes, I will add it myself to the codebase. Where should I adjust the documentation to inform users about the added option?

### Anything else?

[README of Citus Columnar](https://github.com/citusdata/citus/blob/main/src/backend/columnar/README.md)
[Docs of Citus Columnar](https://docs.citusdata.com/en/stable/admin_guide/table_management.html#columnar-storage)

### PR DESCRIPTION
**Pull request by Dennis8**
Added columnar option to PostgreSQL configuration for the table materialization. For more info on columnar, see the Citus documentation: https://docs.citusdata.com/en/stable/admin_guide/table_management.html#columnar-storage

resolves #6052

### Description

I added an additional if statement to the PostgreSQL adapter in order to allow the option to materialize a table in a column-oriented way through Citus Columnar

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/2199).
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

Edit: Have added the changie changelog entry.

### CODE REVIEW

**Comment by colin-rogers-dbt** [comment]
As citus is a new db it would seem to be better long term to create a new adapter for it. This would be similar to how dbt-redshift inherits from dbt-postgres (as it's also a columnar implementation of postgres). @dataders any thoughts here?

**Comment by Dennis8** [comment]
> As citus is a new db it would seem to be better long term to create a new adapter for it. This would be similar to how dbt-redshift inherits from dbt-postgres (as it's also a columnar implementation of postgres). @dataders any thoughts here?

Well, it is not entirely a new database. It's available as an extension of an existing PostgreSQL database. The same as for instance the PostGIS extensions for geospatial capabilities in PostgreSQL. See for instance this documentation how the extension can be activated in an existing PostgreSQL database:
[https://www.citusdata.com/updates/v11-1/#citus-columnar](https://www.citusdata.com/updates/v11-1/#citus-columnar)

**Comment by dataders** [comment]
@Dennis8 very cool! I'm very keen on supporting Citus Postgres users.

@colin-rogers-dbt, I think the Redshift comparison is not that great because you can think of Redshift as a fork of Postgres, whereas Citus is just an extension of pure postgres. Last month, we announced support for GCP's AlloyDB which is postgres "front-end" with the backend swapped out. So zero changes were needed to dbt-postgres to make it compatible. @Dennis8 if you're interested, we'd love to have the support for Citus similarly documented. See https://github.com/dbt-labs/docs.getdbt.com/pull/1926 and [Documenting a new adapter](https://docs.getdbt.com/docs/contributing/adapter-development/5-documenting-a-new-adapter) to get started.

In this case, one change to one parameter does not seem like enough to me to justify a new adapter. @Dennis8 can you envision any other additional syntax that Citus introduces that Citus users of dbt-postgres might want to take advantage of?

**Comment by colin-rogers-dbt** [comment]
Thanks for the clarification! Assuming that we'll only need this (and maybe some minor changes) I agree we don't need a new adapter.

**Comment by Dennis8** [comment]
> In this case, one change to one parameter does not seem like enough to me to justify a new adapter. @Dennis8 can you envision any other additional syntax that Citus introduces that Citus users of dbt-postgres might want to take advantage of?

@dataders, currently I'm just using Citus to make my postgres instance column-oriented as it is more appropriate for data warehousing use cases. So I have not much experience in the other parts of the library of Citus to scale Postgres to clusters, as I'm running just a single instance.

**Comment by colin-rogers-dbt** [comment]
Looks like it's not breaking our current tests, would you mind adding a functional test similar [to this](https://github.com/dbt-labs/dbt-core/blob/10b2a7e7ff906a8317c63d4a86630660729d37f8/tests/functional/postgres/test_postgres_unlogged_table.py)?

**Review by colin-rogers-dbt — CHANGES_REQUESTED** [review]
Looks like it's not breaking our current tests, would you mind adding a functional test similar [to this](https://github.com/dbt-labs/dbt-core/blob/10b2a7e7ff906a8317c63d4a86630660729d37f8/tests/functional/postgres/test_postgres_unlogged_table.py)?

**Comment by ChenyuLInx** [comment]
@colin-rogers-dbt  a functional test might not be possible given that our testing postgres doesn't have the extension. So the syntax might just fail

**Comment by colin-rogers-dbt** [comment]
> @colin-rogers-dbt a functional test might not be possible given that our testing postgres doesn't have the extension. So the syntax might just fail

@ChenyuLInx good point, I just don't like the idea of adding untestable functionality. I wonder if it's worth using the citus extension in our functional testing. @Fleid any thoughts on how much support dbt-postgres needs to provide for columnar postgres?

**Comment by jtcohen6** [comment]
We discussed this some more internally, and I left a comment on the linked issue: https://github.com/dbt-labs/dbt-core/issues/6052#issuecomment-1334207940

**Comment by jtcohen6** [comment]
Going to close this PR, given the rationale on the linked issue

**Pull request closed without merging**
