### PR TITLE
run performance action when code changes in performance dir

### PR DESCRIPTION
**Pull request by kwigley**
### Description

run performance regression workflow when related code changes

### Checklist

- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by kwigley** [comment]
Confirmed that the performance regression workflow (https://github.com/dbt-labs/dbt/runs/3690933662) run when pushing a commit that changes code in `performance/` (https://github.com/dbt-labs/dbt/pull/3946/commits/ed7dbcec21bb66fb430f30ff5d3b599dee3c2cfe) 😎

**Comment by kwigley** [comment]
@nathaniel-may I'll leave to you to see this through 👍

**Comment by nathaniel-may** [comment]
Oh wow this is easy. So the performance regression tests failed this time because they fail all the time right now. I'm thinking we shouldn't merge this till the tests are tuned better so we don't have to be in "rerun hell" to merge changes.

**Comment by nathaniel-may** [comment]
Also your auto-formatter strikes again 🙃

**Comment by kwigley** [comment]
> Also your auto-formatter strikes again 🙃

oh! ignore that file, I had to add some dummy changes to trigger the action 👍

**Comment by kwigley** [comment]
closing, but keep branch as an example

**Pull request closed without merging**
