### PR TITLE
Fix incremental delete+insert SQL

### PR DESCRIPTION
**Pull request by ataft**
resolves https://github.com/dbt-labs/dbt-adapters/issues/150

### Problem

The delete query for the 'delete+insert' incremental_strategy with 2+ unique_key columns is VERY inefficient. In many cases, it will hang and never return for deleting small amounts of data (<100K rows).

### Solution

Improve the query by switching to a much more efficient delete strategy:
```
delete from table1
where (col1, col2) in (
    select distinct col1, col2 from table1_tmp
)

```

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

### CODE REVIEW

**Comment by dbeatty10** [comment]
Thanks for raising this PR @ataft !

Could you resolve the merge conflict?

image

**Comment by ataft** [comment]
Here's the merge conflict message I'm getting:
image

Oddly, I don't see the `global_project` directory in the `main` branch. Not sure what's going on, see here:
https://github.com/dbt-labs/dbt-core/tree/main/core/dbt/include

**Comment by colin-rogers-dbt** [comment]
Hi @ataft sorry for the confusion but we're in the middle of a large scale refactor of dbt.adapters. Once that has been wrapped up (in the next couple weeks) we will move your PR to the new [dbt-adapters](https://github.com/dbt-labs/dbt-adapters) repo and review it there.

More info: https://github.com/dbt-labs/dbt-core/discussions/9171

**Comment by dataders** [comment]
hey @ataft thanks for taking the time to open this PR. Since opening, this code now lives in a separate repo: [dbt-adapters](https://github.com/dbt-labs/dbt-adapters). A consequence of the decoupling is that PR can't be merged anymore as is, so we're closing it. For more context see https://github.com/dbt-labs/dbt-core/discussions/9171.

The linked issue has already been transferred. Please don't hesitate to re-open on the `dbt-adapters` repo.

**Comment by ataft** [comment]
All good, just moved the PR over to https://github.com/dbt-labs/dbt-adapters/pull/151

**Pull request closed without merging**
