### PR TITLE
merge exclude columns for incremental models

### LINKED ISSUE #5260: [CT-656] [Feature] Allow for merge exclude columns
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

Right now, for incremental models using the `merge` strategy, we allow users to specify a specific list of `merge_update_columns` to include in the merge statement. 

For wide, denormalized models, it's likely that users may want/need to exclude only a couple of columns, and update all the rest. Right now, this would require the user to manually specify a potentially long list of all columns that need to be updated, rather than a shorter,  more straightforward list of columns _not_ to update. 

Once incremental materializations are simplified in the effort to create more streamlined materialization code, this seems like a simple quality of life enhancement!

### Describe alternatives you've considered

Create a custom version of `get_merge_sql` to allow for an additional config `merge_exclude_columns` to achieve this behavior. 

### Who will this benefit?

This will be beneficial for users who have wide incremental models, and may need tight controls over the merge behavior on those tables. 

### Are you interested in contributing this feature?

heck yeah

### Anything else?

This was mentioned in the original issue for [`merge_update_columns`](https://github.com/dbt-labs/dbt-core/pull/3100#issuecomment-905301525)

### PR DESCRIPTION
**Pull request by dave-connors-3**
resolves #5260 

### Description

This PR allows a user to specify a list of columns _not_ to update during an incremental run using the merge strategy. This   is achieved via a new macro `get_merge_update_columns` that will take into account user input from either `merge_update_columns` or the new `merge_exclude_columns` config to return the correct set of columns to update. 

This will need to be dispatched to accomodate slightly different behavior in the `dbt-spark` repository.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
Thanks @dave-connors-3! I'm tagging this `ready_for_review`, and adding it to the review queue for the Adapters team.

In order to merge this PR, we'll want a functional test for `merge_exclude_columns` that lives in `dbt-tests-adapter`, and runs successfully when pulled into `dbt-snowflake` + `dbt-bigquery` + `dbt-spark`.

It would make sense for this new test to live alongside the existing tests for `merge_update_columns`. Currently, those tests live only in each adapter plugin, and not yet converted to use the new `pytest` framework:
- [dbt-snowflake: TestIncrementalMergeColumns](https://github.com/dbt-labs/dbt-snowflake/blob/d1653859147263b52b96fe1bfecfee25b50522b9/tests/integration/simple_copy_test/test_simple_copy.py#L277-L310)
- [dbt-bigquery: TestIncrementalMergeColumns](https://github.com/dbt-labs/dbt-bigquery/blob/803b954394efe4e09a7b4b830d9964be47e1525b/tests/integration/simple_copy_test/test_simple_copy.py#L69-L96)
- [dbt-spark: TestDeltaStrategies](https://github.com/dbt-labs/dbt-spark/blob/244742ac0ee35db9774d9830a96d5796bf738448/tests/integration/incremental_strategies/test_incremental_strategies.py#L78)

**Comment by kd2718** [comment]
Our team would love to have this feature. What is the status of this PR?

**Comment by leahwicz** [comment]
@nathaniel-may could this be a PR that you prioritize the team to get some eyes on and review please?

**Review by gshank — APPROVED** [review]
The code here is straightforward and does not look risky. This does not implement adapter zone tests, however, so that should be done in a separate ticket/pr.

**Pull request merged**
