### PR TITLE
add optional shorthand to full refresh command

### LINKED ISSUE #5878: [CT-1204] [Feature] Add shorthand for `--full-refresh` flag
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I write (and misspell!) `--full-refresh` a whole heck of a lot during dbt development. Would love to add a shorthand for that flag in the sameway that `--select` can be reduced to `-s`, `--target` can be reduced to `-t` etc. 

### Describe alternatives you've considered

Keeping on keeping on! There's a tradeoff here between clarity and brevity, so i understand we probably don't want to make every single flag shorthand!

### Who will this benefit?

keyboard users

### Are you interested in contributing this feature?

Yes!

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dave-connors-3**
resolves #5878 

### Description

Adds an optional shorthand for the `--full-refresh` flag!

`dbt build -fr` for an incremental model passes:

image

and acts as expected:

```
[0m16:11:54.082634 [debug] [Thread-7  ]: Began running node model.davebt.incremental
[0m16:11:54.083352 [info ] [Thread-7  ]: 4 of 5 START sql incremental model dbt_dconnors.incremental .................... [RUN]
[0m16:11:54.085262 [debug] [Thread-7  ]: Acquiring new snowflake connection "model.davebt.incremental"
[0m16:11:54.085788 [debug] [Thread-7  ]: Began compiling node model.davebt.incremental
[0m16:11:54.086130 [debug] [Thread-7  ]: Compiling model.davebt.incremental
[0m16:11:54.104372 [debug] [Thread-7  ]: Writing injected SQL for node "model.davebt.incremental"
[0m16:11:54.105039 [debug] [Thread-7  ]: finished collecting timing info
[0m16:11:54.105302 [debug] [Thread-7  ]: Began executing node model.davebt.incremental
[0m16:11:54.153305 [debug] [Thread-7  ]: Writing runtime sql for node "model.davebt.incremental"
[0m16:11:54.154408 [debug] [Thread-7  ]: Using snowflake connection "model.davebt.incremental"
[0m16:11:54.154609 [debug] [Thread-7  ]: On model.davebt.incremental: /* {"app": "dbt", "dbt_version": "1.3.0b2", "profile_name": "dbt_metrics_integration_tests", "target_name": "snowflake", "node_id": "model.davebt.incremental"} */
create or replace transient table development.dbt_dconnors.incremental  as
        (

with 

final as (

    select * from development.dbt_dconnors.mock_incrementing_source

    
)

select * from final
        );
``` 

Opening as a draft for now, assuming I need some testing here, but didn't find a test that quite looked like the right place at first glance!

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
Personally, I like `-fr` ("for real"), though I could also see an argument for `-f` ("force," a la `git push`)

**Comment by gshank** [comment]
I would be happy with just updating one of the existing tests/functional tests that do "--full-refresh" with the new shortcut, such as tests/functional/materializations/test_runtime_materialization.py

**Review by gshank — APPROVED** [review]
Looks good!

**Review by stu-k — APPROVED** [review]
Nothing stands out 👍

**Review by iknox-fa — APPROVED** [review]
LGTM, thanks!

**Review by ChenyuLInx — APPROVED** [review]

**Pull request merged**
