### PR TITLE
Use daff for diff formatting in unit testing

### LINKED ISSUE #8558: [CT-3078] Improve diff displayed in stdout when a test fails
### Description

Currently, a failing unit test simply logs both the actual and expected results to stdout:

```sh
❯ dbt unit-test
20:34:18  Running with dbt=1.7.0-b1
20:34:18  target not specified in profile 'postgres', using 'default'
20:34:18  Registered adapter: postgres=1.7.0-b1
20:34:19  Found 10 models, 3 seeds, 20 tests, 0 sources, 0 exposures, 0 metrics, 360 macros, 0 groups, 0 semantic models, 5 unit tests
20:34:19  Found 1 unit test, 2 models, 0 sources, 0 exposures, 0 metrics, 360 macros, 0 groups, 0 semantic models
20:34:19  
20:34:19  Concurrency: 1 threads (target='default')
20:34:19  
20:34:19  1 of 1 START unit_test my_model__test_my_model ................................. [RUN]
20:34:19  1 of 1 FAIL 1 my_model__test_my_model .......................................... [FAIL 1 in 0.11s]
20:34:19  
20:34:19  Finished running 1 unit_test in 0 hours 0 minutes and 0.53 seconds (0.53s).
20:34:19  
20:34:19  Completed with 1 error and 0 warnings:
20:34:19  
20:34:19  Failure in unit_test my_model__test_my_model (models/unit_testing/schema.yml)
20:34:19    

Actual:
| c |
| - |
| 3 |

Expected:
| c |
| - |
| 4 |

20:34:19  
20:34:19    compiled code at target/compiled/jaffle_shop/models/unit_testing/schema.yml/models/unit_testing/my_model__test_my_model.sql
20:34:19  
20:34:19  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

This may work fine for very small expected results (few rows & columns), but would be difficult to debug for larger results as the diff is not visualized. For example: 


```sh
❯ dbt unit-test
...
Found 1 differing row between actual and expected outputs for my_model:
Actual
- {'c': 3}
          ^
Expected
+ {'c': 4}
```

### Acceptance Criteria   

Test failure message displays diff in a readable format                                                                                  
                                                                                                                                                         
### Impact to other teams
                  
None                 
                                
### Will backports be required?
                                                                                                         
No              

### Context

### PR DESCRIPTION
**Pull request by MichelleArk**
resolves #8558

### Problem

The diff is pretty lackluster for unit tests when they fail!

### Solution
* Use `daff` to determine and render the diff between `actual` and `expected`
* strip out colors from `daff` rendering if `NO_COLORS` option is specified
* update the `UnitTestDiff` in the result to include more structure - the actual json rows, expected json rows, and rendered diff. 

Note: There are quite a few moving pieces on this branch right now. I think we should add tests for unit test artifacts but it may make more sense to do once they are integrated into build/test commands since that will affect the results. 

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

🎩 
```
03:20:50  Completed with 1 error and 0 warnings:
03:20:50  
03:20:50  Failure in unit_test my_model__test_my_model_string_concat (models/unit_testing/schema.yml)
03:20:50    

expected differs from actual:

@@ ,string_c
+++,ab
---,abc
```

Screenshot 2023-11-01 at 11 46 25 PM
Screenshot 2023-11-01 at 11 47 10 PM

### CODE REVIEW

**Comment by dbeatty10** [comment]
@MichelleArk This is super useful to compare and contrast some of our formatting options!

### Summary
When kooking at a larger unit test case, it's possible to pick out the differences when using a colorized [daff](https://paulfitz.github.io/daff/) (**da**ta di**ff**).

But when looking at a naive tabular output, I wasn't able to discern the differences between the actual and expected.

Non-colorized daff is much harder to see than a colorized daff. But it is still easier that the naive tabular output due to:
- the side-by-side nature
- reduced number of rows
- "→" to signal where to look

Our most readable formats may have similar characteristics as well.

See below for more details.

### Crux of the issue

The crux of the issue is being able to determine two things:
1. Did the unit tests all pass or not?
1. If one or more didn't pass, what was the difference between the actual output and the expected output?

### Relevant factors
It will be interesting to see how the following affects our ability to put our finger on what the actual diffs are:
- number of columns
- number of rows
- data types
- length of the values
- etc.

### 2 columns by 10 rows; 2 differences

Here's a "bigger" example to compare/contrast with. Would be useful if we can up up with even more representative examples.

<details>

<summary>

### Project setup
</summary>

1. `git clone https://github.com/dbt-labs/dbt-core.git`
1. `cd dbt-core`
1. `git checkout spike/daff-formatting-unit-testing`
1. Follow the [contributing](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#virtual-environments) instructions:
    1. Create and activate a virtual environment
    1. `pip install -r dev-requirements.txt -r editable-requirements.txt`
    1. etc.
1. Create a dbt project (i.e., create a `dbt_project.yml` file that points to a database connection profile)

</details>

<details>

<summary>

### Files
</summary>

`actual.csv`
```csv
uuid4_1,uuid4_2
bace1187-8b38-4b35-90b0-a4399ab62891,c4cef639-49ad-4ec8-8d65-e45acb2d2e6b
b8f759ab-83e5-4b46-ba6c-26e0e8a65ce9,ea1ce868-e9be-4099-b6b0-6e080f16c8fa
40fa0f5c-e5d3-4e88-bd73-bacc2496a346,47ca2417-91e5-49cd-b82d-8398a513ff61
4769f4f0-51a0-4b7f-aa3a-d7547e131011,6ce2c256-d85d-4d6c-a7a5-07e5f82ae4be
89a94808-88d7-4fdf-85d4-d19b0cbb5193,c5b1419c-a2d0-4358-92a4-df05cb82c989
c97fc0ce-6dd5-40c5-8fc0-459be00cb2a1,fc5eab42-460b-4970-a28d-e15d8e79eeda
3cd99b8c-0829-4a26-a854-1938944606af,9266c041-e81b-40bd-9cbb-b0bbfe3a4450
b883eba0-867f-4f03-88f0-e20adea4dead,39f8c21b-788f-4612-a7b0-3aaa887f658c
bc3ae058-b1e6-46fa-9706-002e341658ab,502e6acd-1b41-40ed-afa0-5488b2492ffc
b9e0d99c-c7c5-4663-a75e-2774ebe69e7b,a4fad314-3afa-4cf5-8382-830fc70cc44f
```

`expected.csv`
```
uuid4_1,uuid4_2
bace1187-8b38-4b35-90b0-a4399ab62891,c4cef639-49ad-4ec8-8d65-e45acb2d2e6b
b8f759ab-83e5-4b46-ba6c-26e0e8a65ce9,ea1ce868-e9be-4099-b6b0-6e080f16c8fa
40fa0f5c-e5d3-4e88-bd73-bacc2496a346,47ca2417-91e5-49cd-b82d-8398a513ff61
4769f4f0-51a0-4b7f-aa3a-d7547e131011,6ce2c256-d85d-4d6c-a7a5-07e5f82ae4be
89a94808-88d7-4fdf-85d4-d19b0cbb5193,c5b1419c-a2d0-4358-92a4-df05cb82c989
c97fc0ce-6dd5-40c5-8fc0-459be00cb2a1,934bf0f9-8f74-47b5-8ac5-7bb7c750e498
3cd99b8c-0829-4a26-a854-1938944606af,f7ff7645-2add-46ea-bcb6-8ca1301a34a1
b883eba0-867f-4f03-88f0-e20adea4dead,39f8c21b-788f-4612-a7b0-3aaa887f658c
bc3ae058-b1e6-46fa-9706-002e341658ab,502e6acd-1b41-40ed-afa0-5488b2492ffc
b9e0d99c-c7c5-4663-a75e-2774ebe69e7b,a4fad314-3afa-4cf5-8382-830fc70cc44f
```

`models/my_model.sql`
```sql
select 'bace1187-8b38-4b35-90b0-a4399ab62891' as uuid4_1, 'c4cef639-49ad-4ec8-8d65-e45acb2d2e6b' as uuid4_2 union all
select 'b8f759ab-83e5-4b46-ba6c-26e0e8a65ce9' as uuid4_1, 'ea1ce868-e9be-4099-b6b0-6e080f16c8fa' as uuid4_2 union all
select '40fa0f5c-e5d3-4e88-bd73-bacc2496a346' as uuid4_1, '47ca2417-91e5-49cd-b82d-8398a513ff61' as uuid4_2 union all
select '4769f4f0-51a0-4b7f-aa3a-d7547e131011' as uuid4_1, '6ce2c256-d85d-4d6c-a7a5-07e5f82ae4be' as uuid4_2 union all
select '89a94808-88d7-4fdf-85d4-d19b0cbb5193' as uuid4_1, 'c5b1419c-a2d0-4358-92a4-df05cb82c989' as uuid4_2 union all
select 'c97fc0ce-6dd5-40c5-8fc0-459be00cb2a1' as uuid4_1, 'fc5eab42-460b-4970-a28d-e15d8e79eeda' as uuid4_2 union all
select '3cd99b8c-0829-4a26-a854-1938944606af' as uuid4_1, '9266c041-e81b-40bd-9cbb-b0bbfe3a4450' as uuid4_2 union all
select 'b883eba0-867f-4f03-88f0-e20adea4dead' as uuid4_1, '39f8c21b-788f-4612-a7b0-3aaa887f658c' as uuid4_2 union all
select 'bc3ae058-b1e6-46fa-9706-002e341658ab' as uuid4_1, '502e6acd-1b41-40ed-afa0-5488b2492ffc' as uuid4_2 union all
select 'b9e0d99c-c7c5-4663-a75e-2774ebe69e7b' as uuid4_1, 'a4fad314-3afa-4cf5-8382-830fc70cc44f' as uuid4_2
```

`models/_unit.yml`
```yaml
unit:
    - model: my_model
      tests:
        - name: test_my_model
          description: "unit test description"
          given: []
          expect:
            rows:
              - {uuid4_1: bace1187-8b38-4b35-90b0-a4399ab62891, uuid4_2: c4cef639-49ad-4ec8-8d65-e45acb2d2e6b}
              - {uuid4_1: b8f759ab-83e5-4b46-ba6c-26e0e8a65ce9, uuid4_2: ea1ce868-e9be-4099-b6b0-6e080f16c8fa}
              - {uuid4_1: 40fa0f5c-e5d3-4e88-bd73-bacc2496a346, uuid4_2: 47ca2417-91e5-49cd-b82d-8398a513ff61}
              - {uuid4_1: 4769f4f0-51a0-4b7f-aa3a-d7547e131011, uuid4_2: 6ce2c256-d85d-4d6c-a7a5-07e5f82ae4be}
              - {uuid4_1: 89a94808-88d7-4fdf-85d4-d19b0cbb5193, uuid4_2: c5b1419c-a2d0-4358-92a4-df05cb82c989}
              - {uuid4_1: c97fc0ce-6dd5-40c5-8fc0-459be00cb2a1, uuid4_2: 934bf0f9-8f74-47b5-8ac5-7bb7c750e498}
              - {uuid4_1: 3cd99b8c-0829-4a26-a854-1938944606af, uuid4_2: f7ff7645-2add-46ea-bcb6-8ca1301a34a1}
              - {uuid4_1: b883eba0-867f-4f03-88f0-e20adea4dead, uuid4_2: 39f8c21b-788f-4612-a7b0-3aaa887f658c}
              - {uuid4_1: bc3ae058-b1e6-46fa-9706-002e341658ab, uuid4_2: 502e6acd-1b41-40ed-afa0-5488b2492ffc}
              - {uuid4_1: b9e0d99c-c7c5-4663-a75e-2774ebe69e7b, uuid4_2: a4fad314-3afa-4cf5-8382-830fc70cc44f}              
```

```shell
dbt run -s my_model
dbt unit-test
```

</details>

### Option 1 - naive tabular

```shell
git checkout unit_testing_feature_branch
dbt unit-test
```

image

### Option 2 - daff (w/ colorization)

```shell
git checkout spike/daff-formatting-unit-testing
dbt unit-test
```

image


### Option 3 - daff (w/o colorization)

```shell
git checkout spike/daff-formatting-unit-testing
dbt --no-use-colors unit-test
```

image

**Comment by MichelleArk** [comment]
Overall I think the daff-based diff is a definite improvement over the naive tabular diff that's current implemented. It's much clearer to see what the diff actually is - especially with coloring :) My only concern is that the daff package has not had a [python release in a while (last release was in 2020](https://pypi.org/project/daff/)). 

The [project itself seems to be active](https://github.com/paulfitz/daff) and supports many languages, and there is [an issue open to release a more recent python package](https://github.com/paulfitz/daff/issues/191). I'd probably just recommend we hard-pin this dependency if we want to go forward with it since a new version could include years of changes.

Otherwise - the stdout diff feels like an interface we can continue to change if we wanted to between minor versions. What's important is to standardize on a diff output in the json artifact that can be stable and consistent between different visualization implementations for the initial release though. 

cc @gshank - how does that sound to you in terms of proceeding here?

**Review by gshank — APPROVED** [review]
Very nice!  And it has the side benefit of giving us a reason to have variables and methods named "daff_diff" :-)

**Comment by MichelleArk** [comment]
Sneak peek of diff visualization for array types! (on bigquery, not quite working with postgres yet...)

Screenshot 2023-11-15 at 11 27 09 AM

**Pull request merged**
