### PR TITLE
unit test config

### LINKED ISSUE #8294: [CT-2921] Create special unit testing Config object
The initial unit testing branch specifies TestConfig in model_config.py, but actually uses NodeConfig (from ParsedNode) in the UnitTestNode. Make a custom UnitTestConfig with appropriate fields and use in UnitTestNode.

Is this actually required?  We're now selecting against standard model nodes, and the database/schema/identifier is also coming from the model nodes. So it's not clear what we would need from a specialized Config object.

### PR DESCRIPTION
**Pull request by MichelleArk**
resolves #8294
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#  

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by MichelleArk** [comment]
I'm seeing the same `mypy` failure on the `unit_testing_feature_branch` branch: https://github.com/dbt-labs/dbt-core/actions/runs/6111537160/job/16586993751?pr=8411

```sh
core/dbt/context/providers.py:1507: error: Argument 1 to "contextmember" has incompatible type "Callable[[UnitTestContext, str, Optional[str]], str]"; expected "Optional[str]"  [arg-type]
```

**Comment by gshank** [comment]
That mypy error for contextmember was also seen in a mypy pr that Quigley did. Let me merge main into the feature branch...

**Comment by gshank** [comment]
Oh, I think '@contextmember' needs to be changed to '@contextmember()'

**Comment by MichelleArk** [comment]
> I suspect we'd get schema changes if we ran the script to build it though. 

good point! I updated manifest/v11.json in this commit so we can keep track of where the changes were necessary but won't backfill the artifact tests as this PR is already getting pretty big.

**Comment by MichelleArk** [comment]
@dbt-labs/cloud-artifacts - these changes going onto a feature branch so don't need review quite yet as they will not be released until the feature branch is merged (which will tag the CA team for review at that point)

**Pull request merged**
