### PR TITLE
Update v0.21 changelog: confusing note about breaking change to Snowflake transactions

### PR DESCRIPTION
**Pull request by jtcohen6**
resolves https://github.com/dbt-labs/dbt-core/issues/4732

### CODE REVIEW

**Comment by jtcohen6** [comment]
Going to get all sorts of failing tests, since this is against `0.21.latest` :)

**Comment by leahwicz** [comment]
@jtcohen6 do we want to update this in the GitHub release notes section as well?

**Review by leahwicz — APPROVED** [review]

**Comment by jtcohen6** [comment]
[already did!](https://github.com/dbt-labs/dbt-core/releases/tag/v0.21.0#:~:text=sources%20(%233236%2C%20%233408)-,dbt-snowflake,-Breaking%3A%20Turn%20off)

**Comment by jtcohen6** [comment]
(Turning off branch protection rules so I can merge in this update to `CHANGELOG.md` only, then I'll turn them right back on)

**Pull request merged**
