### PR TITLE
Improve docker image README

### LINKED ISSUE #8211: [CT-2870] [Bug] Incorrect examples in docker README
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The README file located in the directory for the Dockerfile has incorrect commands and inconsistent spacing between arguments.

- The command indicated in "Running an image in a container" is missing a newline escape
- There are two whitespaces before the --target flag in the examples and between other parameters
- Markdown script end markers are indented wrong
- Unnecessary newline escapes in two of the commands suggested 

### Expected Behavior

The README should provide commands that are functional and the style for the shell script should be consistent within the README file.

### Steps To Reproduce

For example, execute the command for "Running an image in a container" as indicated by the README file

### Relevant log output

```shell
N/A
```

### Environment

```markdown
N/A
```

### Which database adapter are you using with dbt?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jamezrin**
Resolves #8211   

### Problem

This PR solves the nitpicks mentioned in the #8211 issue.

### Solution

These are straighforward changes to documentation:

- Fix unnecessary/missing newline escapes
- Remove double whitespace between parameters
- 2-space indent for extra lines in image build commands

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by dbeatty10** [comment]
@cla-bot check

**Comment by dbeatty10** [comment]
Thanks for submitting this @jamezrin !

This looks good to me. One thing:
- Could you run `changie new` to create an changelog entry and commit the result?

More detailed instructions [here](https://github.com/dbt-labs/dbt-core/blob/b1d931337e5bf4063f6ef76e3993bd5abe425a13/CONTRIBUTING.md#adding-or-modifying-a-changelog-entry).

**Comment by jamezrin** [comment]
> Thanks for submitting this @jamezrin !
> 
> This looks good to me. One thing:
> 
> * Could you run `changie new` to create an changelog entry and commit the result?
> 
> More detailed instructions [here](https://github.com/dbt-labs/dbt-core/blob/b1d931337e5bf4063f6ef76e3993bd5abe425a13/CONTRIBUTING.md#adding-or-modifying-a-changelog-entry).

Done :)

**Review by ChenyuLInx — APPROVED** [review]
@jamezrin  Thanks for making this README better!

**Pull request merged**
