### PR TITLE
Backport 8210

### LINKED ISSUE #8284: Backport #8210
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In #8210, we reduced the number of distinct events fired when displaying node failure errors. In order to facilitate faster troubleshooting, we want to backport the change. The Experience team (@davidharting) has requested that we initially release the change in an RC (potentially 1.6.1rc1), so that changes can be validated in IDE 1.2 before final release. Before final release, customer support (@patkearns10) has also requested notice.

### Describe alternatives you've considered

_No response_

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by peterallenwebb**
resolves #8284

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by peterallenwebb** [comment]
@davidharting @patkearns10 [In this thread](https://dbt-labs.slack.com/archives/C04N364M8QY/p1690559367320729) you asked for a heads-up so that you would know when this is getting back-ported to 1.6, so this is your notification that is happening very soon!

**Comment by davidharting** [comment]
@peterallenwebb Is this already available in 1.7-prerelease? I'm trying to identify the best way for me to test out this behavior.

**Comment by peterallenwebb** [comment]
@davidharting Yes. It's in 1.7.

**Review by graciegoheen — APPROVED** [review]
Critical flow tests of IDE have been completed - we're ready to rock and roll!

**Pull request merged**
