### PR TITLE
parse + compile `constraint.to` and `constraint.to_columns` on foreign key constraints

### PR DESCRIPTION
**Pull request by MichelleArk**
resolves https://github.com/dbt-labs/dbt-core/issues/8062
associated dbt-adapters PR: https://github.com/dbt-labs/dbt-adapters/pull/260

### Problem

Because you must hard-code your database.schema.table name when setting a foreign key constraint:
* DAG dependencies are incorrect
* multi-environment is not supported (it's very hacky)
* This feature has become more important now that warehouses use foreign key constraints for better performance.

### Solution

During parsing: 
* parse the ref or source expressions
* validate valid jinja ref/source expression
* populate node.refs and/or node.sources based on fk 'to' fields

During compilation:
* User the adapter class to render a relation, transforming the 'raw' 'to' field to a relation identifier.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

### CODE REVIEW

**Comment by MichelleArk** [comment]
For docs: 

Model-level constraint example syntax: 
```
models:
  - name: my_model
    constraints:
      - type: foreign_key
        columns: [id]
        to: ref('my_model_to') | source('source', 'source_table')
        to_columns: [id]
    columns:
      - name: id
        data_type: integer
"""
```

Column-level example syntax:
"""
models:
  - name: my_model
    columns:
      - name: id
        data_type: integer
        constraints:
        - type: foreign_key
          to: ref('my_model_to') | source('source', 'source_table')
          to_columns: [id]
"""

**Comment by MichelleArk** [comment]
I'd like to do the following tidying in a follow-up (to not bloat this PR scope): 
* delete adapters test_constraints.py
* move primary key constraint testing to tests/constraints
* use new static jinja rendering method for unit test `ref` and `source` resolution

**Review by gshank — APPROVED** [review]
Looks good. Nice tests.

I do have one question -- it might be possible to do some of this at parse time. Did doing it that way get too weird? Or did it feel like it had more affinity to compilation time than parse time?

**Comment by MichelleArk** [comment]
> I do have one question -- it might be possible to do some of this at parse time. Did doing it that way get too weird? Or did it feel like it had more affinity to compilation time than parse time?

That's a great question. I initially did a lot more of this at compile time but was able to move the initial syntax validation, and dependency lookup to parse-time. At compile time the only thing that happens is that the `to` field of constraints is rendered to a relation. This felt appropriate to do at compilation time as it depends on an adapter (e.g. quoting config) to render a relation.

There is error-handling in compilation for sanity's sake but I don't expect syntax errors (e.g. invalid ref syntax) to be caught during compilation phase since parsing was run first.

**Comment by MichelleArk** [comment]
Some final 🎩 
(contracted has fk constraint to my_other_model)

```sh
❯ dbt run --select +contracted
21:57:00  Running with dbt=1.9.0-a1
21:57:00  target not specified in profile 'postgres', using 'default'
21:57:01  Registered adapter: postgres=1.9.0-a1
21:57:01  Found 22 models, 6 seeds, 20 data tests, 6 sources, 13 metrics, 716 macros, 6 semantic models, 5 unit tests
21:57:01  
21:57:02  Concurrency: 1 threads (target='default')
21:57:02  
21:57:02  1 of 2 START sql table model test_arky.my_other_model .......................... [RUN]
21:57:02  1 of 2 OK created sql table model test_arky.my_other_model ..................... [INSERT 0 1 in 0.21s]
21:57:02  2 of 2 START sql table model test_arky.contracted .............................. [RUN]
21:57:02  2 of 2 ERROR creating sql table model test_arky.contracted ..................... [ERROR in 0.07s]
21:57:02  
21:57:02  Finished running 2 table models in 0 hours 0 minutes and 0.60 seconds (0.60s).
21:57:02  
21:57:02  Completed with 1 error and 0 warnings:
21:57:02  
21:57:02    Database Error in model contracted (models/marts/contracted.sql)
  insert or update on table "contracted__dbt_tmp" violates foreign key constraint "contracted__dbt_tmp_id_fkey"
  DETAIL:  Key (id)=(7) is not present in table "my_other_model".
  compiled Code at target/run/jaffle_shop/models/marts/contracted.sql
21:57:02  
21:57:02  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

**Comment by ekarabulut-r7** [comment]
Thank you @MichelleArk ! with this fix, we will clear many `post_hook`s from our models :)

**Comment by elyobo** [comment]
This is a great addition, thanks @MichelleArk.

**Comment by caileyfitzgerald** [comment]
Is this just for dbt-core or also for dbt-cloud?

**Comment by MichelleArk** [comment]
This is implemented in dbt-core, so its definitely for dbt-core as well as dbt Cloud. It will go out in the next minor version (1.9) of dbt-core!

**Pull request merged**
