### PR TITLE
fix docs typo

### LINKED ISSUE #5195: [CT-585] [Bug] minor typo in dbt-cli docs for parse command
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the output from the cli for the parse command reads

```
    parse               Parsed the project and provides information on performance
```

### Expected Behavior

it should read "Parses the project"

### Steps To Reproduce

run dbt command with no args

### Relevant log output

_No response_

### Environment

```markdown
- OS: Mac OS X
- Python: 3.9.12
- dbt: 1.0.4
```

### What database are you using dbt with?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bavardage**
resolves #5195

### Description
Fix minor typo in cli docs

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by bavardage** [comment]
I have signed the CLA - how do I retrigger the check?

**Comment by jtcohen6** [comment]
@cla-bot check

**Review by iknox-fa — APPROVED** [review]
LGTM

**Comment by iknox-fa** [comment]
@cla-bot check

**Pull request closed without merging**
