### PR TITLE
Flexibilize MarkupSafe pinned version

### PR DESCRIPTION
**Pull request by adamantike**
### Description

The current `MarkupSafe` pinned version has been added in #4746 as a temporary fix for #4745.

However, the current restrictive approach isn't compatible with other libraries that could require an even older version of `MarkupSafe`, like Airflow `2.2.2` [0], which requires `markupsafe>=1.1.1, <2.0`.

To avoid that issue, we can allow a greater range of supported `MarkupSafe` versions. Considering the direct dependency `dbt-core` has is `Jinja2==2.11.3`, we can use its pinning as the lower bound, which is `MarkupSafe>=0.23` [1].

This fix should be also backported this to `1.0.latest` for inclusion in the next v1.0 patch.

[0] https://github.com/adamantike/airflow/blob/2.2.2/setup.cfg#L125
[1] https://github.com/pallets/jinja/blob/2.11.3/setup.py#L53

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have added information about my change to be included in the [CHANGELOG](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry).

### CODE REVIEW

**Comment by adamantike** [comment]
Not sure if a change like this one would require a changelog entry. Open to suggestions!

**Comment by iknox-fa** [comment]
@adamantike Thanks for your PR.. a changelog entry for this would be great!

**Review by iknox-fa — APPROVED** [review]
LGTM

**Comment by adamantike** [comment]
Thanks for the quick reply! So, to validate before adding it to the changelog, would this be applicable to be backported to `1.0.x`? 

In case it is, should I add the changelog entry for that here too, or do you take care of that when cherry-picking the change?

**Comment by ChenyuLInx** [comment]
@adamantike we changed our changelog system to [changie](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-changelog-entry) so all you need to do is follow the instruction in the link and the actual `changelog.md` will be generated during release. 
@iknox-fa is there a reason we are fixing the upper bound version of `MarkUpSafe` we can use? I think the `install_requires` is usually only used for lower bound unless there's a good reason to cap the version.

**Comment by adamantike** [comment]
Thanks, I have added the changelog entry after following the `changie` instructions.

Regarding why we need to provide an upper bound, it's because of this discussion: https://github.com/pallets/jinja/discussions/1602. `jinja` didn't fix it in their side because version 2.x isn't supported anymore, so `dbt-core` requires this pinning until the `jinja2` dependency can be upgraded to version 3.x.

**Comment by ChenyuLInx** [comment]
@adamantike  Thanks for contributing!!!

**Comment by adamantike** [comment]
Thanks for the quick resolution!

With this PR merged, is there a formal process to ask for this fix to be backported to `1.0.latest`?

**Comment by stu-k** [comment]
@adamantike Thanks again for the contribution! Our team will handle backporting your change!

**Pull request merged**
