### PR TITLE
Rename "constraints_enabled" to "contract"

### LINKED ISSUE #6748: [CT-1916] Rename 'constraints_enabled' to 'contract'
In the foundational [dbt Constraints work](https://github.com/dbt-labs/dbt-core/pull/6271), we added a boolean config named `constraints_enabled` that “turns on” contracting for this model. Given that the scope of model contracts is broader than “constraints,” and that dbt’s enforcement may go beyond the built-in behavior of analytical data platforms, we should rename this config to `contracted` instead.

### PR DESCRIPTION
**Pull request by gshank**
resolves #6748

### Description

After more discussion and considering the scope of this setting, we decided to rename  "constraints_enabled" to "contract".

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Review by MichelleArk — APPROVED** [review]
Changes here look good! There is some boilerplate in each adapter implementation that references `config.get('constraints_enabled')` ([dbt-snowflake example](https://github.com/dbt-labs/dbt-snowflake/pull/341/files#diff-79f8a1393fce3d64ce05238ec32cdf841b7ed89cf053ece9de0c50d763d3db79R25)), which will need to be updated as well. I can make corresponding issues in the adapter repos 👍

**Comment by MichelleArk** [comment]
We should close the corresponding adapter issues prior to merging this to prevent breaking tests in adapters, since they inherit from [functional tests modified in this PR](https://github.com/dbt-labs/dbt-core/pull/7002/files#diff-8cb7e0269a9b9a6117115f688e3a6eafc9d4924df1a7e44a320f5cd06a3dd63cR22).

**Comment by gshank** [comment]
We can't close the adapter issues prior to merging this because the "contract" config wouldn't actually exist in core until after this is merged. The has to merge first, then all of the adapter issues.

**Comment by gshank** [comment]
Actually, I have a question about this now that I think about it. We're "promoting"  the "contract" attribute to the model level. Shouldn't we be accessing it via the model, like "model.contract", and not looking at the config? This is one of those fields where the config is just used to shuttle the value in node level...

**Comment by gshank** [comment]
So actually the config.get calls should still work in the adapter repos since it doesn't require that the config attribute actually work. But if we did model.contract they might fail.

**Comment by sungchun12** [comment]
@gshank thanks for evolving contracts by actually having the config called `contract`. Even that simple visual cue as I tested this out today was so much more intuitive than `constraints_enabled`.

**Pull request merged**
