### PR TITLE
Issue 6444 grant username quotes

### LINKED ISSUE #6444: [Bug] Grants fails to correctly quote username when revoking
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

As part of the new grants feature, https://docs.getdbt.com/reference/resource-configs/grants dbt will attempt to revoke users not part of the grant before reapplying users listed in the grant. 
DBT does this (at least in the Redshift adaptor ) by pulling the table permissions and explicitly looping through every user then using a revoke command like 
revoke select on "database"."schema"."table" from user1, user2 ;
The user is not quoted so a user like user.name will fail with 
syntax error at or near "."
  LINE 2: ...user1, user.name, user2...

I am fairly certain the macro in https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/adapters/apply_grants.sql line 82 just needs some quotes

### Expected Behavior

the revoke command should quote users
revoke select on "database"."schema"."table" from "user1", "user2" ;

### Steps To Reproduce

Create a user with a period in the name for example in Redshift 
create user "first.last";

Create a simple dbt incremental model and user the grant syntax to give permission to that table within dbt.

Run DBT twice (on the first run the revoke macro is not run as the table is new)

### Relevant log output

_No response_

### Environment

```markdown
- OS:Ubuntu 20.04
- Python: 3.8.10 
- dbt: 1.3.1
```

### Which database adapter are you using with dbt?

redshift

### Additional Context

_No response_

### LINKED ISSUE #8751: [Bug] Postgres + Grants + Username-With-Dashes does not work
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I configure grants in DBT for a postgres database and a db role like 'foo-bar' I get postgres syntax errors because the name is not quoted. 

If I try to quote it like "\"foo-bar\"" it works for the grants part but breaks in the incremental grants part. Looks like some places do not strip and some places do strip those extra quotes I added to my db role name. 

### Expected Behavior

I should not have to put in extra quotes - DBT should be able to create the appropriate database syntax for supported role names. 

### Steps To Reproduce

Create a postgres role with dashes in the name. 

Try to have DBT assign grants to that user - it will break. 
Add manual quotes - it will work. 

Try to make a incremental model with those same grants - it will break. 

### Relevant log output

_No response_

### Environment

```markdown
- OS: macOS ventura 13.6
- Python: 3.10.12
- dbt: 1.6.2
```

### Which database adapter are you using with dbt?

postgres

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by barton996**
resolves #6444 resolves #8751

### Problem
For models with grants, where the corresponding table is not new (model has been run before), dbt revokes all grants on this table by looping through all users with table permissions.

The macro currently does not surround the user names that it reads from the table permissions with quotes, meaning that revoke statements on users with usernames like first.last will fail. 

This is problematic when granting to a user GROUP, as you cannot control what is returned by the table permissions query using your grant yaml config e.g. `grants: select: ["GROUP developers"]`.

### Solution
apply_grants.sql jinja template is updated so that usernames are surrounded with adapter.quote() character when granting and revoking.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [x] I have run this code in development and it appears to resolve the stated issue  
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [x] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

### CODE REVIEW

**Comment by dbeatty10** [comment]
@cla-bot check

**Comment by barton996** [comment]
> Thank you for your pull request and welcome to our community. We could not parse the GitHub identity of the following contributors: **Fraser Barton**. This is most likely caused by a git client misconfiguration; please make sure to:
> 
> 1. check if your git client is configured with an email to sign commits `git config --list | grep email`
> 2. If not, set it up using `git config --global user.email email@example.com`
> 3. Make sure that the git commit email is configured in your GitHub account settings, see https://github.com/settings/emails

@dbeatty10 I filled in this cla with [this link](https://docs.google.com/forms/d/e/1FAIpQLScfOV7K4enYRHozrDRP6BBIXjOij-JDGca6WBTHyP_ANXSqlg/viewform?usp=sf_link), followed the steps asked by the cla-bot and since done a commit. What have I missed?

**Comment by dbeatty10** [comment]
@barton996 it looks like these first two commits are the ones that the cla-bot is barking about:

image

I'm guessing the fix is a force push as described here:
https://stackoverflow.com/questions/41349644/commit-with-wrong-username-to-github

Wanna give that a shot and let me know how it goes?

**Comment by graciegoheen** [comment]
Looks like we're still getting an error here - do you want to just start over with a new branch & new PR? Looks like the changes were pretty small, so it may be faster to just copy & paste the code changes in this situation @barton996

**Review by mikealfare — APPROVED** [review]

**Comment by barton996** [comment]
> Looks like we're still getting an error here - do you want to just start over with a new branch & new PR? Looks like the changes were pretty small, so it may be faster to just copy & paste the code changes in this situation @barton996

Apologies I meant to do that on Monday. I'll do it now

**Comment by mikealfare** [comment]
After looking at some ways to "fix" the two commits that @dbeatty10 pointed out, that seems like unnecessary effort. @graciegoheen's method will work. You can also squash merge your changes into another branch on your fork via a PR, which would become a new commit that's definitely signed (because you're doing it in GH). Then just update the branch on this PR to that new branch.

**Comment by barton996** [comment]
Replaced by https://github.com/dbt-labs/dbt-core/pull/8809

**Pull request closed without merging**
