### PR TITLE
Reformat core [CT-104 CT-105]

### LINKED ISSUE #3195: [CT-105] use black code formatter
Let's introduce the automated code formatting to dbt as long as it does not sacrifice readability. As the codebase matures, it will be nice to not have to think about formatting, generate clean diffs, and maintain a single code style.

[black code formatter docs](https://black.readthedocs.io/en/stable/)

First, run on a subset of files and get feedback from contributors about stylistic decisions. We may need to tweak line length and other knobs to our liking.
Then:
- Add `black` as a dev dependency
- Update `tox.ini` and where tox code checks are run in CI and Makefile. May need 2 different tox envs, one to check formatting and one to actually run the formatter
- Get the changes above reviewed
- Finally, create a commit that runs the formatter on the whole repo and set the author of the commit to a machine user so we can easily determine blame history.

### PR DESCRIPTION
**Pull request by iknox-fa**
resolves #3195 and #3196 (CT-104, CT-105)

### Description

The results of running the pre-commit code in [this PR](https://github.com/dbt-labs/dbt-core/pull/4639) vs main.
Note that the commits were made using [git-black](https://github.com/AlayaCare/git-black) and therefor maintain the correct history.

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change

### CODE REVIEW

**Comment by iknox-fa** [comment]
@leahwicz do you know if we can disable the CLA bot for this?  Each commit is made as it's original committer, many of which pre-date the cla-bot.

**Comment by leahwicz** [comment]
@cla-bot check

**Comment by leahwicz** [comment]
@cla-bot check

**Comment by leahwicz** [comment]
@iknox-fa when you are ready to merge let me know and we can coordinate on the CLA check. We might have to remove it as required and then close/reopen the PR and then merge

**Pull request merged**
