### PR TITLE
[CT-271] [Feature] not_null test selects column instead of *

### LINKED ISSUE #4769: [CT-271] [Feature] `not_null` test selects column instead of *
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The built in test for `not_null` writes SQL equivalent to:

```sql
SELECT *
FROM model
WHERE column IS NULL
```

On databases like BigQuery this ends up being quite expensive when compared to:

```sql
SELECT column
FROM model
WHERE column IS NULL
```

### Describe alternatives you've considered

_No response_

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

PR ready to go

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by willbowditch**
resolves #4769

### Description

Currently the `not_null` test writes SQL equivalent to 

```sql
SELECT *
FROM model
WHERE column IS NULL
```

Which on columnar databases like BigQuery makes running the test more expensive than

```
SELECT column
FROM model
WHERE column IS NULL
```

This PR changes the test to `SELECT column`, unless the store failures feature is enabled, in which case it is useful to keep the failing rows in totality using `SELECT *`.

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change

### CODE REVIEW

**Comment by willbowditch** [comment]
@drewbanin I have signed the CLA.

No changes to tests in the PR at the moment, but happy to have a go at adding some if they're needed.

**Comment by leahwicz** [comment]
@cla-bot check

**Review by ChenyuLInx — APPROVED** [review]
Looks good to me

**Comment by leahwicz** [comment]
@willbowditch I had to close and reopen the PR to pick up on some new GitHub Checks that we just added. One is around how we do the Changelog and that's what failing here. So sorry for the inconvenience! Would you mind updating the Changelog entry to follow our new process that you can see documented [here](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-changelog-entry)

**Comment by willbowditch** [comment]
Hey @leahwicz - no worries, I've reverted the changes to the markdown changelog and pushed up the file `changie` created

**Pull request merged**
