### PR TITLE
Remove UnsetProfileConfig

### PR DESCRIPTION
**Pull request by MichelleArk**
resolves https://github.com/dbt-labs/dbt-core/issues/5539

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
`MP_CONTEXT` - gosh - there's some gnarliness here:
https://github.com/dbt-labs/dbt-core/blob/8217ad4722c9b4ce99be3bf3a96ba7b92bec22a7/core/dbt/flags.py#L120-L126

Agree it really doesn't belong on the `flags` object / module. It's probably just there because that's where we've historically stuck a lot of our globals. It does seem to be used for [locks within `dbt-core`](https://github.com/dbt-labs/dbt-core/search?q=MP_CONTEXT) (when things need to be thread-safe), and [also within `dbt-rpc`](https://github.com/dbt-labs/dbt-rpc/search?q=MP_CONTEXT).

**Comment by gshank** [comment]
I tried looking through some of the test failures and in at least one case I saw an error about "unable to serialize SpawnContext", which is from that. The test output started disappearing though...

**Comment by MichelleArk** [comment]
> I tried looking through some of the test failures and in at least one case I saw an error about "unable to serialize SpawnContext", which is from that. The test output started disappearing though...

@gshank - Thank you for looking into the type `TypeError: Object of type SpawnContext is not JSON serializable` errors, and for the additional context @jtcohen6! Integration tests on the feature/click-cli branch are expected to fail [since we started running integration tests](https://github.com/dbt-labs/dbt-core/pull/6387) through the new click framework which under development and still missing large portions of its implementation. This issue does feel out of scope for this PR but I've opened an issue to track it as part of the API-ification epic: https://github.com/dbt-labs/dbt-core/issues/6509.

**Review by iknox-fa — APPROVED** [review]
LGTM!

**Comment by iknox-fa** [comment]
> > I tried looking through some of the test failures and in at least one case I saw an error about "unable to serialize SpawnContext", which is from that. The test output started disappearing though...
> 
> @gshank - Thank you for looking into the type `TypeError: Object of type SpawnContext is not JSON serializable` errors, and for the additional context @jtcohen6! Integration tests on the feature/click-cli branch are expected to fail [since we started running integration tests](https://github.com/dbt-labs/dbt-core/pull/6387) through the new click framework which is under development and still missing large portions of its implementation. This issue does feel out of scope for this PR but I've opened an issue to track it as part of the API-ification epic: #6509.

+100 from my POV.  I think this one falls into the overarching de-globalization effort that @ChenyuLInx will be working on at some point as tech-lead of the "gap work" for dbt-server.

**Pull request merged**
